### ISSUE TITLE
Bookworm takes a long time to open large plane text documents

### ISSUE THREAD

**Issue by DraganRatkovich** [blindpandas/bookworm#104]
## Describe the Problem

An error was encountered when opening a text file larger than 900 kb. It really takes a long time for a bookworm to process a file, while other document formats larger than 11MB open in just seconds. I opened a 1MB text file and Bookworm processed it in almost 1 minute, at the same time I opened a 26MB pdf and it took 2 seconds to open. @mush42 Could you look at the code what is going on. The log does not show any errors because Bookworm opens the file without any problems, it just takes a long time before a normal .txt file opens.
## To Reproduce

1. Open bookworm;
2. Open a text file larger than 1MB;
3. see the result
## Expected behavior

Bookworm should open a .txt file in just a second because it processes .pdf, .doc files larger than 20MB in just a second.
## The File You've Opened

.txt
## Desktop (please complete the following information):

OS: Windows 10 X64 bit;
Bookworm version: Latest;
Settings not changed!

**Comment by mush42** [comment]
Hi @DraganRatkovich 

I couldn't reproduce this issue in my machine. I tried a 3.2 MB document and it opens in a matter of seconds. Here are the details of the file I opened:

* Document length: 3.28 MB (3445595 bytes)
* Lines: 18,035
* Words: 550,680
* Characters: 3,403,675

Please tell us more about the document you opened, and upload the problematic file if possible.

Specifically, what language the document is in?

Best

Musharraf

**Comment by DraganRatkovich** [comment]
Hello @mush42 The document I opened is in Georgian language, with the encoding utf-8, 1667419 characters and 28459 lines in total.

**Comment by mush42** [comment]
Hello @DraganRatkovich 

Would you mind trying a large English plane-text document and reporting your experience?

I suspect that the issue is due to document language.

Also, I'm waiting for others to way in this issue.

Best
Musharraf

**Comment by mush42** [comment]
@DraganRatkovich 
The plane text issue has been fixed; the fix has been tested and confirmed.
The encoding tip was a great help. Thanks.

**Comment by DraganRatkovich** [comment]
@mush42 Thank you for your fix and the hard work you put into making this program amazing.

**Comment by DraganRatkovich** [comment]
@mush42 Sorry for the late reply, yes, I downloaded it, everything works fine, the .txt file opens quickly and smoothly, thank you.
