### ISSUE TITLE
Error when opening Bookworm

### ISSUE THREAD

**Issue by DraganRatkovich** [blindpandas/bookworm#105]
## Describe the Problem
Today I reinstalled Windows and when I tried to open Bookworm I encountered the following error:

Traceback (most recent call last):
  File "bookworm\i18n\core.py", line 70, in set_locale
  File "gettext.py", line 592, in translation
FileNotFoundError: [Errno 2] No translation file found for domain: 'bookworm'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "bookworm\bookworm.py", line 51, in main
  File "bookworm\bootstrap.py", line 206, in run
  File "bookworm\bootstrap.py", line 196, in run
  File "bookworm\bootstrap.py", line 176, in init_app_and_run_main_loop
  File "bookworm\bootstrap.py", line 132, in setupSubsystems
  File "bookworm\i18n\core.py", line 88, in setup_i18n
  File "bookworm\i18n\core.py", line 83, in set_locale
  File "bookworm\platform_services\_win32\user.py", line 21, in set_app_locale
TypeError: property is read-only.
@mush42 What could be the problem?
## To Reproduce

Honestly not sure because I just opened Bookworm and got the above error, not sure if I need to install something or not. I have all the Visual C++ Redistributables, the runtime, and all other libraries installed correctly. The bookworm executable is not read-only in properties.
## Expected behavior

The bookworm should open without problems
## Desktop (please complete the following information):

OS: Windows 10 Pro x64 bit;
Bookworm version: 2022.1.0.5 Portable.

**Comment by DraganRatkovich** [comment]
@mush42 When I looked at several documents online related to this error, the problem seems to be related to the locales import section in the __init__.py file. Not sure if this is true or not, but could you take a look at it?

**Comment by DraganRatkovich** [comment]
@mush42 Still the same problem, tried Portable as well as Installer.

**Comment by mush42** [comment]
Well, I pushed a tentative fix, I'll upload a build for you to try ASAP.

**Comment by DraganRatkovich** [comment]
ok

**Comment by DraganRatkovich** [comment]
@mush42 Sorry, now realized that my OS is missing .net framework I installed it and Bookworm runs without problems, but still if you can build with the latest commits that would be great, because in my previous release where I talked about the problem with opening a Georgian document, now I tried with an English document and Bookworm opened it's only seconds, so it's best to get an already fixed build with new commits before release if possible.
