### ISSUE TITLE
Comments and bookmarks are not announced during reading

### ISSUE THREAD

**Issue by dreinn** [blindpandas/bookworm#107]
- Define a bookmark or a comment and ensure that in preferences checkboxes about announcing comments and bookmarks when jumping are active.
- If you use a screen reader or press f5 for reading, no sound or announce is provided when you are near to that comment or bookmark.

## Desktop (please complete the following information):

 - OS: Win10 64bit.
 - 
 - Bookworm version 2022.1a5

## Additional context

I'm using the portable version on a pc with no admin rights

**Comment by mush42** [comment]
Hello @dreinn 

If I understood you correctly, you want your screen reader to announce the presence of a Bookmark/note when you reach a line containing a bookmark/note.

If so, I regret telling you that this feature is not currently supported in Bookworm.

What we currently support is the announcement of bookmarks when you jump between bookmarks within a document using F2 and shift + F2. And the indication of notes using a small sound.

Best
Musharraf

**Comment by mush42** [comment]
@dreinn 

It is possible to support what you're asking for with the built-in text-to-speech. If you want this feature, please open another issue for a feature request.

Best
Musharraf
