### ISSUE TITLE
Unable to run from source

### ISSUE THREAD

**Issue by TheQuinbox** [blindpandas/bookworm#108]
## Describe the Problem
WHen running
```shell
invoke run
```
I get an error about the .NET framework V4 not being installed, and that I need to install it.
## To Reproduce
I just followed the running instructions in the readme.
## Expected behavior
Bookworm should run from source without issues.
## The File You've Opened
N/A
## Desktop (please complete the following information):
 - OS: Windows 10 64-bit
 - Bookworm version: Latest source
 - Recent settings you may have changed in Bookworm: N/A

## Additional context
When going to the link the terminal output gives me, I get an installer. I've run it, but still get the same result.

**Comment by mush42** [comment]
Hello @TheQuinbox 

Do you have Visual Studio 2019 installed?

Installing Visual Studio 2019  community may resolve this issue, and probably other issues down the rapid whole as well.

To successfully build a fully-featured version of Bookworm, the build script builds some dynamic libraries to support Windows Universal Platform features, e.g. support for one core voices.

Best
Musharraf
