### ISSUE TITLE
Allow selection of more than one language in the OCR Scan dialog for a document

### ISSUE THREAD

**Issue by DraganRatkovich** [blindpandas/bookworm#112]
@mush42 I'm not entirely sure if this should be opened here or not, but if I'm wrong, please let me know exactly where I should open this issue.
Currently, Bookworm only allows you to select one language for scanning a book with OCR, which in turn will make unreadable parts of the document that are in another language but not selected in the scan language dialog.
## Describe alternatives you've considered
If possible, allow the user to select the languages ​​of the document in which the document was created. For example, I had a test document containing English and Georgian words, OCR successfully scanned the Georgian part, but did not scan and mistook the English words for Georgian, which made the English part completely unreadable.
If there are some translated books, for example, from English to another language, but still the author's name and some materials are in English, the ability to select English and another language with English will make the scanning results of the document in that specific and in English clearly.

**Comment by mush42** [comment]
Hello @DraganRatkovich 

That's a really good suggestion!

Tesseract supports using multiple languages simultaneously, but the same is not true for Windows UWP OCR.

I'll implement this ASAP.

Best
Musharraf

**Comment by DraganRatkovich** [comment]
@mush42 It would be very helpful and convenient.

**Comment by DraganRatkovich** [comment]
@mush42 Any news here?

**Comment by mush42** [comment]
@DraganRatkovich 
I will tackle this issue next.

**Comment by mush42** [comment]
Hello @DraganRatkovich 

Please test the latest build and tell us whether your issue has been resolved.

Best
Musharraf

**Comment by DraganRatkovich** [comment]
Hi @mush42
Tested right now, works very well, scan result is clear, thanks.
