### ISSUE TITLE
Can't close window after scanning image to text with OCR when displaying results

### ISSUE THREAD

**Issue by DraganRatkovich** [blindpandas/bookworm#113]
## Describe the Problem
Just discovered this issue when I scanned one image to text today. When OCR results are displayed from a scanned image, you cannot close it. No ctrl+w helps. The only solution is to close the whole program and reopen it. Also, saving to a text file is disabled, so it cannot be clicked to save image results to a text file.

## To Reproduce
1. Open bookworm;
2. Go to the OCR menu and click Image to Text;
3. Select one image, select the appropriate OCR language, and wait for the scan to complete.

You will see the result in the window, but you will not be able to close it, since the standard gesture for closing the current document, namely ctrl+w, does not work there.

## Expected behavior
The bookworm should close the results and return to the main empty text area.

## Desktop (please complete the following information):
* OS: Windows 10 Pro x64 bit
* Bookworm version: 2022.1b1 (downloaded from AppVeyor, can also be reproduced in the current version, which can be found on the website and in the Github releases section.)
* Last settings changed: N/A

## Additional context
@mush42 Is there some gesture I'm missing, or can you look into this issue?

**Comment by DraganRatkovich** [comment]
@mush42 Please refer to this after the unicode issue has been resolved, and issue 112, which also really needs to be fixed.

**Comment by DraganRatkovich** [comment]
@mush42 Is there any news regarding to this issue?

**Comment by mush42** [comment]
@DraganRatkovich 
This is very easy to fix. It is a matter of time.

**Comment by DraganRatkovich** [comment]
@mush42 Hope this gets fixed.

**Comment by mush42** [comment]
@DraganRatkovich 
This has been fixed in the latest build. Please test.

**Comment by cary-rowen** [comment]
Hi @mush42 @DraganRatkovich 
Thanks for your hard work.
I tested this and I can now close the recognition results with ctrl+w, but I'm having trouble trying to save the recognition results as.
When I save as text, bookworm shows a progress dialog, but it doesn't respond for a long time, I'm sure my recognition result is only a few dozen words, it won't take that long.

thanks

**Comment by mush42** [comment]
Hello @cary-rowen  @DraganRatkovich 

The issue is a purely GUI issue. The document is actually saved to a plane text file, but the progress window will be shown indefinitely.
