### ISSUE TITLE
take note

### ISSUE THREAD

**Issue by wesenalemu** [blindpandas/bookworm#118]
## Describe the Problem
the function of bookworm to take note does not work. control+n does not work. The option to take note is not also found in the anotation menu.
A clear and concise description of what the problem is.

## To Reproduce

1. Go to '...'anotation
3. See error

## Expected behavior
"take note" would appear

## The File You've Opened

Tell us what is the format of the file you've opened [e.g. PDF]. If possible, attach the file you have open in Bookworm when the problem happened.
any PDF file
## Desktop (please complete the following information):

 - OS: [e.g. Windows 10 64-bit]
 - Bookworm version Bookworm-0.4b1
 - Recent settings you may have changed in Bookworm [e.g. changed the speech settings]

## Additional context

I am unable to take note using bookwarm. I tried the latest versions. it was working in the previous version released in 2020 which I don't even currently have. The short cuts related with note taking do not work and it is not also found in the menu. The option for exporting note is not also found.

Likewise, I noticed issue on bookmark. Control shift+b does not bring list of bookmarks rather enables to create named bookmark. I hope you correct this problem on the latest issues.

**Comment by cary-rowen** [comment]
I'm a little confused,
Hope you can fill out the template
Thanks

**Comment by wesenalemu** [comment]
@cary-rowen In the previous version of Bookworm, I was able to take note using CTRL+N keyboard short cut. Now, this does not work in the latest versions such as Bookworm-0.4b1. All options related with note taking capability of bookworm are not working.

**Comment by DraganRatkovich** [comment]
Hello @wesenalemu
I didn't know that Bookworm had an option to take notes, I only know of a feature to add comments which works very well with all the documents I've tried. Use the keyboard shortcut ctrl+m to add comments at any time.
@cary-rowen Does the user mean by note taking this commenting feature?

**Comment by cary-rowen** [comment]
Hi @DraganRatkovich 
I guess what @wesenalemu said should also be the feature of Ctrl+M.

**Comment by cary-rowen** [comment]
Hi @wesenalemu 
You can try the latest 2022.1A5 and see if you can find the features you need.
Thanks

**Comment by DraganRatkovich** [comment]
There are no notes in the annotation menu, only commenting, highlighting, etc. I think this is what @wesenalemu needs.

**Comment by wesenalemu** [comment]
@DraganRatkovich 
the user guide of bookworm says that it has note taking feature. It was also working in previous versions. 2022.1a5 does not also have that feature. I didn't mean comment feature. I have pasted below from the user guide which is related with the features I am looking for.

"Taking Notes
While reading a document, you can press Ctrl + N (or select the "Take Note" menu item from the "Annotations" menu to take a note. The note will be added at the current position of the cursor. You'll be asked to provide the title and the content for the note. Type the desired title and content, and then click the OK button. A note will be added at the current location.
When you navigate to a page containing at least one note, you will hear a little sound indicating the existence of a note in the current page..
Managing Notes
Press Ctrl + Shift + N, or select the "Manage Notes" menu item from the "Annotations" menu. A dialog containing added notes will be shown. Clicking any item in the notes list will immediately take you to the position of that note. Clicking the "View" button will bring up a dialog showing the title and the content of the selected note.
Additionally, you can click the "Edit" button to edit the title and the content of the selected note, press F2 to edit the title of the selected note in place, or you can click the "Delete" button or the "Delete" key on your keyboard to remove the selected note.
Exporting Notes
Bookworm allows you to export your notes to a plain-text file, or to an HTML document which you can then open in your web browser. Optionally, Bookworm allows you to export your notes to markdown, which is a text-base format for writing structured documents popular among expert computer users.
To export your notes, follow these steps:
1. From the "Annotations" menu select the "Notes Exporter..." menu item
2. Select the export range. This tells Bookworm whether you want to export the notes of the whole document, or you just want to export the notes of the current section.
3. Select the output format. This determines the format of the file you get after exporting. Exporting to a plain-text gives you a simple, nicely formatted text file, exporting to HTML gives you a web page, and exporting to markdown gives you a markdown document which is a text format popular among expert computer users.
4. If you want Bookworm to open the file to which your notes have been exported, you can check the "Open file after exporting" checkbox.
5. Click Export. You will be asked to select the file name of the exported file, and the location to which the file is saved. Clicking "Save" will save the file, and open it if you have instructed Bookworm to do so."

**Comment by DraganRatkovich** [comment]
@wesenalemu Maybe they don't update the user manual to match the latest changes. The note-taking feature, I think, has been removed in recent versions. My Bookworm does not have this feature.

**Comment by wesenalemu** [comment]
@DraganRatkovich 
I think you are right. The note taking feature was however very interesting feature. The short cut for viewing and adding bookmark is also slightly changed. How can I ask the developers to add the note taking feature in the latest products?

**Comment by wesenalemu** [comment]
@mush42 
can you bring the note taking functionality to life and use the previous short cuts for viewing and adding bookmark? these features make bookworm beyond reader of books and helps us to talk with the books too. these two issues are the interest of many blinds.

**Comment by mush42** [comment]
Hello @wesenalemu 

Actually, nothing has changed in Bookworm with regard to annotations. I just renamed a few features and changed the keyboard shortcuts accordingly.
* Take note has been renamed to add comment, and the keyboard shortcut has been changed to Ctrl+M. Other than that, add comment  is the same as take note.
* A list of bookmarks, comments (i.e. notes), and highlights can be opened from the annotations menu 
* The shortcut Ctrl+N has been assigned to opening a new instance of Bookworm in recent versions
* All of the annotation features can be easily found in the context menu of the main content text box\

PS: the user guide is out of date, even for v0.4b1. So it is not accurate at all.

What causes this confusion is my obsessive focus on code at the expense of updating the user guide.
My bad!

If someone can help with updating the English user guide I will be grateful. 

Best
Musharraf

**Comment by wesenalemu** [comment]
@mush42 
Thank you so much! That was helpful.
If you have time, please consider the following:
•	Add keyboard short cut preference for users. This can save time and can be used for assigning a keyboard short cut that does not clash with other. For me, CTRL+n is not totally working for instance.
•	Include option to rename name of bookmark. Currently, I am not able to rename bookmark using f2.
•	I am not hearing any sound when there is comment. 
I will update the user guide and share you once I get time
