### ISSUE TITLE
Allow TTS Voice pitch change

### ISSUE THREAD

**Issue by DraganRatkovich** [blindpandas/bookworm#119]
Currently, Bookworm allows you to change the speed of the selected TTS voice, but there is no possibility of changing the pitch, while other TTS readers allow you to change the pitch.
## Describe the solution you'd like
Add the ability to change the pitch of the selected voice in the settings menu, in the appropriate category with the rate parameter. I know there are voice profiles available, however they are useless in this case, in any case, the pitch control should be available in the settings dialog.
@mush42 Is it possible to implement this?

**Comment by mush42** [comment]
@DraganRatkovich 
For SAPI 5, it is possible. For onecore, I'm not sure.

**Comment by DraganRatkovich** [comment]
@mush42 It would be nice to implement this for Sapi5 voices, even if it's not possible for OneCore.

**Comment by DraganRatkovich** [comment]
@mush42 Are there any plans here?

**Comment by mush42** [comment]
@DraganRatkovich 
Yes the fix is coming.
These days , My time is limited due to some academic obligations.

Best
Musharraf

**Comment by mush42** [comment]
@DraganRatkovich 
Next up is this one. Please bear with me.

**Comment by DraganRatkovich** [comment]
@mush42 It's nice to see big changes, I'm looking forward to this one as well.
