### ISSUE TITLE
Announce the section title when changing sections using Alt+Down/UpArrow

### ISSUE THREAD

**Issue by mush42** [blindpandas/bookworm#121]
### Discussed in https://github.com/blindpandas/bookworm/discussions/120

<div type='discussions-op-text'>

<sup>Originally posted by **cary-rowen** March  6, 2022</sup>
Hi @mush42 

Press Alt + Up/Down Arrow in the text of the document to switch chapters of the document, NVDA should report the current chapter timely.
I don't know if this is an NVDA bug or if Bookworm is not sending notifications.

Thanks</div>

**Comment by cary-rowen** [comment]
Hi @mush42 
I have tested this and it works great, thanks for your effort.
Grateful
Cary
