### ISSUE TITLE
Windows10OCR recognition result is empty

### ISSUE THREAD

**Issue by cary-rowen** [blindpandas/bookworm#124]
## Describe the Problem
Empty results when using Windows10OCR to recognize documents or pictures
## To Reproduce

1. Change the default OCR engine to "Windows10OCR" in Bookworm preferences;
2. Select "Image To Text..." in the OCR menu;
3. Try to recognize the image;
4. The recognition result is empty;
5. Change the default OCR engine to "Tesseract OCR Engine" in Bookworm 
6. Repeat steps 2 and 3, making sure to select the same image.
7. The recognition results can be displayed.

## Expected behavior
After performing step 4, the recognition result can be displayed.

## The File You've Opened
Any image file containing text.

## Desktop (please complete the following information):

 - OS: Windows 10 21H2 (x64) build 19044.1526
 - Bookworm version 2022.1b1
 - Recent settings you may have changed in Bookworm: Default recognition engine changed to windows10OCR

## Additional context
The language I use is Simplified Chinese, and the recognition language is also Simplified Chinese.
Whether or not a secondary language is selected has no effect on this issue, and the recognition results are all empty.
So it's not a regression by #112.

**Comment by cary-rowen** [comment]
Hi @draganRatkovich 
Can you reproduce this? I want to confirm if this is a bug specific to the Simplified Chinese language.
Thanks

**Comment by DraganRatkovich** [comment]
Hello @cary-rowen
How can I reproduce this? I didn't even know that Windows 10 OCR supports Chinese, and I don't have any Chinese documents and, most importantly, I don't know anything in Chinese.

**Comment by DraganRatkovich** [comment]
@cary-rowen Unfortunately, Windows 10 with built-in OCR does not support my native languages, so I only have the opportunity to test English text, which, at least in the latest build, works quite well.

**Comment by mush42** [comment]
Hi @cary-rowen 

I cannot reproduce this using Both English and Arabic languages. Recognition works well in both cases.

Does the log show anything?
Does recognition work in previous versions?

Best
Musharraf

**Comment by cary-rowen** [comment]
Hi @DraganRatkovich @mush42 
Thanks for testing this, I tested 2022.1a2 and can reproduce this too.
Below is my log, sorry I didn't provide it in the first place.
```
ERROR - bookworm.bookworm.bootstrap - 12/03/2022 09:10:06 - MainThread (11180):
Invalid or unknown document uri: nul
Traceback (most recent call last):
  File "bookworm\bootstrap.py", line 72, in _open_arg_file
  File "bookworm\document\uri.py", line 104, in from_base64_encoded_string
  File "base64.py", line 133, in urlsafe_b64decode
  File "base64.py", line 87, in b64decode
binascii.Error: Incorrect padding
ERROR - bookworm.bookworm.ocr.ocr_menu - 12/03/2022 09:10:42 - MainThread (11180):
Error getting OCR recognition results.
Traceback (most recent call last):
  File "bookworm\ocr\ocr_menu.py", line 417, in _process_ocr_result
  File "concurrent\futures\_base.py", line 439, in result
  File "concurrent\futures\_base.py", line 391, in __get_result
  File "concurrent\futures\thread.py", line 58, in run
  File "bookworm\ocr_engines\base.py", line 81, in preprocess_and_recognize
  File "bookworm\platform_services\_win32\docr_engine.py", line 43, in recognize
ValueError: Error: Language 'zh-cn' is not supported by the OCR engine
```

**Comment by cary-rowen** [comment]
Hi @mush42 
I am amazed at how 《efficiently you fix bugs, great work. thank you very much.
Cheers

**Comment by mush42** [comment]
@cary-rowen does the above fix resolve your issue?

**Comment by cary-rowen** [comment]
Hi @mush42 
Yes, that fix solved my problem perfectly.
Grateful

**Comment by DraganRatkovich** [comment]
Hello @mush42
Looks like my email address couldn't send a message, so sorry for the double post.
The commit 5af31b3 failed the AppVeyor check, but the following commits passed the check. Will they fix this failed check?

**Comment by mush42** [comment]
@DraganRatkovich 
Appveyor is doing very funny things with builds these days. I might consider moving to GitHub actions ASAP.

**Comment by DraganRatkovich** [comment]
@mush42 Can we download new versions after every commit like in AppVeyor?

**Comment by mush42** [comment]
@DraganRatkovich 
Yes. It offers the same functionality.

**Comment by cary-rowen** [comment]
Hi @mush42 
I sent you a private email last week, can you take a look at the trash?
My email address is manchen_0528@outlook.com
Thanks

**Comment by mush42** [comment]
@cary-rowen  I edited your comment to redact your email address.

**Comment by cary-rowen** [comment]
Hi @mush42 
thank you this is great
Cheers

**Comment by DraganRatkovich** [comment]
Hello @mush42
Commit 5af31b3 failed to pass AppVeyor check.
Will it affect next commits?
