### ISSUE TITLE
Error parsing document URL to read

### ISSUE THREAD

**Issue by DraganRatkovich** [blindpandas/bookworm#126]
## Describe the Problem
When parsing the URL of a document from Wikipedia or any other site containing text, Bookworm throws an error: Document not found and huge errors are shown in the log.

## To Reproduce
1. Open Bookworm;
2. Press ctrl+u to go to the URL dialog box;
3. Use [this](https://en.wikiquote.org/wiki/Immanuel_Kant) url or any url you want

## Expected behavior
The bookworm should parse the URL correctly, at least in previous versions it parsed without errors.

## Desktop (please complete the following information):
* OS: Windows 10 21H2X64-bit
* Bookworm version: 2022.1b1X64/X86Portable

@mush42 The log files that I will be uploading here had several almost identical lines that I uploaded in #125 
[error.log](https://github.com/blindpandas/bookworm/files/8234433/error.log)
[wx.log](https://github.com/blindpandas/bookworm/files/8234434/wx.log)

Here is the error log with debug mode enabled.
[debug.log](https://github.com/blindpandas/bookworm/files/8234554/debug.log)

**Comment by mush42** [comment]
Hello @DraganRatkovich 

This is an issue with binaries produced by AppVeyor. My local builds do not have these issues.

I just pushed a commit. Let's see if it fixes the issue.

Best
Musharraf

**Comment by DraganRatkovich** [comment]
Fixed via d767506
