### ISSUE TITLE
Error when searching Georgian article in Wikipedia

### ISSUE THREAD

**Issue by DraganRatkovich** [blindpandas/bookworm#127]
## Describe the Problem
When searching Wikipedia for any article in Georgian and, accordingly, in Georgian letters, Bookworm only shows English articles if there is a matching article with almost the same title.
There are errors in the log, which I will publish at the end of the issue

## To Reproduce
1. Open Bookworm and press Alt+w, then W again to open the Wikipedia search interface.
2. Paste the text below and press Enter to search.
ილია ჭავჭავაძე
3. You will notice that the Bookworm will show the results in English with the name Ilya Chavchavadze, but the Bookworm should show the article in Georgian instead.
## Expected behavior
Instead, Bookworm should search in the selected and typed language instead of only parsing English articles.
## Desktop (please complete the following information):
* OS: Windows 10 21H2X64-bit
* Bookworm Version: Any bookworm version, doesn't matter
* Recent settings changed: N/A
@mush42 Am I missing something here, or is Bookworm only supposed to parse an article from the English-language Wikipedia database? I also want to inform you that inserting a URL parses an article in Georgian very well and shows it in Bookworm.
[WikipediaErrors.log](https://github.com/blindpandas/bookworm/files/8237452/WikipediaErrors.log)

**Comment by mush42** [comment]
@DraganRatkovich 

Better late than never!

**Comment by DraganRatkovich** [comment]
@mush42 Absolutely agree!
