### ISSUE TITLE
Error when trying to read an article from Wikipedia

### ISSUE THREAD

**Issue by DraganRatkovich** [blindpandas/bookworm#130]
## Describe the Problem
When trying to find the Wikipedia article, Bookworm couldn't and opened another article with a different title, but a few of the words were identical. Later, while trying to find the lead singer of the band, which article I wanted to read, Bookworm found several articles, including the main article I was looking for, and when I pressed enter, it again failed to open the document and in the log, errors are displayed. Note that article URL parsing works quite well, I tried it and I was able to read it.
Here's the <details><summary>log information</summary>
<p>
ERROR - bookworm.bookworm.webservices.wikiworm - 13/03/2022 14:11:26 - MainThread (3928):
Failed to get definition from Wikipedia
Traceback (most recent call last):
  File "bookworm\webservices\wikiworm.py", line 103, in view_wikipedia_definition
  File "concurrent\futures\_base.py", line 439, in result
  File "concurrent\futures\_base.py", line 391, in __get_result
  File "concurrent\futures\thread.py", line 58, in run
  File "bookworm\webservices\wikiworm.py", line 88, in define_term_using_wikipedia
  File "wikipedia\wikipedia.py", line 276, in page
  File "wikipedia\wikipedia.py", line 299, in __init__
  File "wikipedia\wikipedia.py", line 345, in __load
wikipedia.exceptions.PageError: Page id "power wolf" does not match any pages. Try another id!
</p>
</details>
@mush42 I think the wikipedia engine needs to be fully checked because it doesn't find the article and the issue #127 still needs to be looked into.

**Comment by DraganRatkovich** [comment]
@mush42 Have you seen this issue and #127?

**Comment by mush42** [comment]
@DraganRatkovich 
Yes. I'm investigating the root cause.

**Comment by DraganRatkovich** [comment]
@mush42 Do you have any news here?

**Comment by mush42** [comment]
@DraganRatkovich 

Please check if you can reproduce this issue with the latest build.

**Comment by DraganRatkovich** [comment]
@mush42 Everything works very well. Thank you for your work. You can close this.
