### ISSUE TITLE
For a Word document, make table of contents elements clickable

### ISSUE THREAD

**Issue by DraganRatkovich** [blindpandas/bookworm#135]
## Is your feature request related to a problem? Please describe.
Can be considered a problem

## Describe the solution you'd like

I couldn't think of a more descriptive name than this, but after describing the problem, I hope everything will be clear, and if the name needs to be changed, well, do it.

In a Word document, if the content of the document is formatted as a table of contents, the Word document displays hyperlinks that, when clicked, navigate the user to the content that the name clicked on and referenced by the content.

Currently, Bookworm has a standard built-in table of contents feature that works quite well, and when you click on any content title, it seamlessly navigates to that content, but in the document, when a tab is pressed and moved out of Bookworm's TOC feature, the formatted text of the table of contents is displayed as standard readable text, which does not navigate to the desired content when clicked, only the heading navigation and the standard Bookworm table of contents function help in the document.

## alternatives

Make the hyperlinks properly visible so that the user can directly click on the desired link at any time without having to go back to Bookworm's Table of Contents feature. If this is implemented, both functions can be used at the same time.

@mush42 I hope I have correctly described what I mean by this function, if not, please let me know and I will attach a test document for your convenience.

**Comment by mush42** [comment]
@DraganRatkovich 
Please try navigate through links using k. And when you land on a link, you can press control + enter to navigate to the Target of that link.
As a bonus, you can press control + shift + enter to go back to the original link.
Support for links is common to all HTML based document formats including word, epub, and actual HTML documents.

**Comment by DraganRatkovich** [comment]
@mush42 I have already tried using K to navigate links, so I opened a issue. Also in the issue comment, it is very well described that there is not a single link in the Word document, the sections where there should be links are only readable, there is no link. For an .epub document, K works for navigating links, but again, they are not clickable and the link doesn't lead to the right section, only Bookworm's TOC feature helps navigate through the chapters.

**Comment by mush42** [comment]
@DraganRatkovich 
Ok. I understand.
Let me investigate this further.

Regarding links, do you mean that links do not work in most situations?

Best
Musharraf

**Comment by DraganRatkovich** [comment]
Hi @mush42
Links do not appear in the document if the Word document contains a table of contents. Instead, Bookworm's TOC feature can only be used in this case for chapter navigation. Sections where there should be links are visible only as text, there are no links there.
If you want I can create a document to test this.

**Comment by mush42** [comment]
@DraganRatkovich 
If you can provide a test document, that would be beter.

Best
Musharraf

**Comment by DraganRatkovich** [comment]
@mush42 Sorry for the late reply, here is a test document.
[testing.docx](https://github.com/blindpandas/bookworm/files/8313812/testing.docx)

**Comment by mush42** [comment]
Hello @DraganRatkovich 

Before testing the fix, please clear the documents cache by removing the folder named .bookworm in your user folder. For instance:
C:\Users\ragan\.bookworm

Best
Musharraf

**Comment by cary-rowen** [comment]
Hi @mush42 
I tested it with the test sample provided by @DraganRatkovich and it works fine,
thanks for your efforts.

**Comment by DraganRatkovich** [comment]
Hello @mush42

Thanks, everything works very well for the Word document, but the only problem left is the .epub document. Again, .epub docs display links very well, but hitting ctrl+enter doesn't help, see this one too please.

**Comment by mush42** [comment]
@DraganRatkovich 
Please provide an example document.

**Comment by DraganRatkovich** [comment]
@mush42 Github does not allow to attach an .epub file, please, use [this direct link](https://gutenberg.org/ebooks/41214.epub.noimages?session_id=4518cb5ac77bfb519eee763321b3713b323fc6e3) to download the document from the Gutenberg Project and test it.
