### ISSUE TITLE
A huge .epub book encoded in utf-8 in Georgian letters takes a long time to process when opened

### ISSUE THREAD

**Issue by DraganRatkovich** [blindpandas/bookworm#145]
I couldn't think of a clearer title than this, so I'll describe the problem under that title.

## Describe the Problem
When converting a Georgian Word document of a book encoded as utf-8 with more than 600 pages into .epub format, Bookworm takes a long time to process and open it, while the same book written in Latin letters opens in a matter of seconds.

I tried two books, with the same page with two encodings, one was written in standard latin letters and the other in georgian letters. The bookworm almost crashed when I tried to open a Georgian written book, and the second one opened in seconds, without any failure.

## To Reproduce
1. Open the Bookworm;
2. Download the attached files and open them with Bookworm.

You will find that the Latin.epub file opens in seconds while the Georgian.epub takes a long time to open.

## Expected behavior
The Bookworm should open both files without any problems within a second.

## Desktop (please complete the following information):

* OS: Windows 10
* Bookworm version: Recent, downloaded from AppVeyor
* Settings changed: none

Here are the files, change .txt to .epub, Github doesn't allow to attach an epub file.
[Georgian.txt](https://github.com/blindpandas/bookworm/files/8361382/Georgian.txt)
[Latin.txt](https://github.com/blindpandas/bookworm/files/8361383/Latin.txt)

@mush42 This issue reminds me #104 when Bookworm needed to open a plain text file encoded in utf-8 and with Georgian letters for a long time.

**Comment by DraganRatkovich** [comment]
@mush42 I forgot to mention you here. First, thanks for fixing #146 Please check out this issue and the attached files when you have time.

**Comment by mush42** [comment]
@DraganRatkovich 
Did the last commit fix the issue for you?
