### ISSUE TITLE
Failed to start Bookworm when opening file from explorer context menu

### ISSUE THREAD

**Issue by shaxzodxasanov** [blindpandas/bookworm#149]
## To Reproduce

1. Go to explorer and find pdf document.
2. Click on contextmenu and open with sub menu then the accesible document reader
3. See error A fatal error has occured. Please check the log for more details.
The log has been written to the file:
C:\Users\xasan\bookworm.errors.log

## The File You've Opened

pdf in russian language
d:\books\python\Мюллер А., Гидо С. - Введение в машинное обучение с помощью Python - 2017\Мюллер А., Гидо С. - Введение в машинное обучение с помощью Python - 2017.pdf

## Desktop (please complete the following information):

 - OS: [e.g. Windows 11 64-bit]
 - Bookworm version [e.g. 2022.a.5]
[Мюллер А., Гидо С. - Введение в машинное обучение с помощью Python - 2017.pdf](https://github.com/blindpandas/bookworm/files/8417523/-.Python.-.2017.pdf)
[bookworm.errors.log](https://github.com/blindpandas/bookworm/files/8417530/bookworm.errors.log)

**Comment by mush42** [comment]
Hello @shaxzodxasanov 

Would you mind providing the content of the file:
C:\Users\xasan\bookworm.errors.log

It contains the actual error details.

Best
Musharraf

**Comment by DraganRatkovich** [comment]
@mush42 There is a log uploaded after the pdf document.

**Comment by DraganRatkovich** [comment]
@shaxzodxasanov I think your problem is similar to the problem that a user in the Telegram group had. Just let me know if you set your file associations correctly when you first installed Bookworm.

**Comment by shaxzodxasanov** [comment]
> @shaxzodxasanov I think your problem is similar to the problem that a user in the Telegram group had. Just let me know if you set your file associations correctly when you first installed Bookworm.

this is portable version. I added bookworm from open with menu on explorer context menu.

**Comment by mush42** [comment]
Opening files from Windows explorer is only possible with an installed version of bookworm.
The integration with Windows explorer is enabled by adding some keys to the registry. Adding those keys, requires administrator access, which is only available during the installation process.
