### ISSUE TITLE
bookworm skips pages while reading PDF

### ISSUE THREAD

**Issue by Junaid4131** [blindpandas/bookworm#150]
## Describe the Problem
bookworm skips pages while reading PDF documents in default reading mode. it was not happening in the initial version, but since the last release, I have been witnessing this issue. often it skips pages when a page is half written, IE: a chapter of a book is about to end, in other cases, it occasionally skips pages while I give the command of say all using NVDA. I tried it with Jaws, but same issue persists. debug mode was also tried, but it did not show any errors 
A clear and concise description of what the problem is.
bookworm's latest release has the issue of skipping pages once we activate say all command using NVDA in a PDF document
## To Reproduce

1. Go to '...open a PDF book.'
2. Click on '....continue reading for several pages.'
3. See error...it will skip one or 2 pages, and this practice will continue later on.

## Expected behavior
it should not have skipped pages in a PDF book. earlier, it worked smoothly once I gave the command of say all. but now, it skips pages and afterwards, I have to go back to the prior page.

## The File You've Opened
I opened a novel (crime and punishment). It is in PDF form. the file has 761 pages and is composed of a fully accessible PDF IE: it can be read in any browser.
Tell us what is the format of the file you've opened [e.g. PDF]. If possible, attach the file you have open in Bookworm when the problem happened.

## Desktop (please complete the following information):

 - OS: [e.g. Windows 10 64-bit]
 - Bookworm version [e.g. 0.1.0b1]
 - Recent settings you may have changed in Bookworm [e.g. changed the speech settings]
laptop of Del with Core I7, 7th generation, windows 10, 64 bit. bookworm version 2022.1a5. I have not  changed any settings yet related to speech or any other.

**Comment by DraganRatkovich** [comment]
Hello @Junaid4131

Please let me know where you downloaded Bookworm from. I ask because there are currently no public releases that contain all the changes listed here in the Github commit sections.

**Comment by cary-rowen** [comment]
The issue appears to have been fixed in the latest build.
