### ISSUE TITLE
Add the ability to restore settings to default

### ISSUE THREAD

**Issue by DraganRatkovich** [blindpandas/bookworm#154]
There is currently no way to restore the default settings in each category.

## Describe the solution you'd like

Add a button to restore default settings in each category, and if possible, also add a button to completely reset Bookworm settings for all categories.

I think adding these two buttons will help users a lot in different scenarios, for example, if they want to reset only reading preferences or another specific category, they can just go to that category and restore default category settings or, if there a full reset is required, they can press the corresponding button and the settings will be reset.

In both cases, a dialog box should also appear informing users that the reset was successful, with an OK button or a close button to close the dialog box.

**Comment by ashleygrobler04** [comment]
Hi there. As said on the tellegram group, I'd love to take on this issue. I've taken a look at the code I might be changing. Just to make sure, each pannel basicly requires a "reset to defaults" button right?
then mabey just before the "Apply" button, a button that says "reset all settings"?

**Comment by DraganRatkovich** [comment]
Hello @ashleygrobler04
Yes, each category requires a button to reset only a certain category and, in addition, a complete reset, which can basically have a name, reset all settings, and which allows you to completely reset Bookworm settings.

**Comment by mush42** [comment]
Hello @ashleygrobler04  @DraganRatkovich 

I don't think we need to have a reset all button. We can just add a menu item to the file menu that can revert all config values to their defaults, and I think even that is unnecessary.

Best
Musharraf

**Comment by DraganRatkovich** [comment]
Hi @mush42
At least one of the options must be enabled, because if the user only wants to reset certain category options, well, the option to do so will be in that category or, if the user needs to do a full program reset, again the corresponding button must exist. Not sure, choose the right one.

**Comment by DraganRatkovich** [comment]
@mush42 Yes, you need to add it to reset all settings to default, but again, it's entirely up to you.

**Comment by cary-rowen** [comment]
I don't think the ability to reset all config is much necessary. Of course this is just my personal opinion.

**Comment by ashleygrobler04** [comment]
Thinking about this, I don't think a reset settings button is needed, since the user can just  go ahead and delete the config files if needed. If a reset  settings button is required, not 1 button for each category, but rather 1 button that resets all the settings entirely.

**Comment by DraganRatkovich** [comment]
@ashleygrobler04 No, deleting configuration files is not suitable for most users. Why do they have to deal with files when a button can do the rest of the work for them? Okay, I understand that you can't just add a reset all settings button, but resetting a category is important!

**Comment by DraganRatkovich** [comment]
@cary-rowen Due to the fact that every program these days supports resetting to default values, I thought it was important.

**Comment by DraganRatkovich** [comment]
@ashleygrobler04 I'm not sure, it's entirely up to you and @mush42 because you can add it as a developer.

**Comment by mush42** [comment]
@ashleygrobler04  Let's implement the reset function for each category.

**Comment by ashleygrobler04** [comment]
Ok, no probs. will do so. I don't know by when I will be done since I got college keeping me busy. Tomorrow is the last day of the week that I will have class, after that I'll start work on it if that is ok with you.
Or if there is a spessific deadline I need to meet let me know.

**Comment by TheQuinbox** [comment]
@ashleygrobler04, any progress on this issue? I'd definitely use this feature.

**Comment by DraganRatkovich** [comment]
Hello,
@ashleygrobler04 Do you have news on this issue?

**Comment by ashleygrobler04** [comment]
Hi there. I am sorry for not doing mutch. I haven't had the time to provide any contributions. College keeps me quite busy and life is just a little too hectic at the moment. Would it be possible for someone else to take care of this issue?

**Comment by DraganRatkovich** [comment]
@mush42 Now all eyes are on you🙂
