### ISSUE TITLE
AccessibleOutput2 causes Bookworm to crash

### ISSUE THREAD

**Issue by mush42** [blindpandas/bookworm#165]
## Describe the Problem

AccesibleOutput2 has some an occasional issue with COM caches that cause Bookworm to fail during startup.
If the issue occurs, then Bookworm won't start unless the faulty COM caches are cleared, or the screen reader output is disabled from within Bookworm's settings.

## To Reproduce
N/A

## Expected behavior

Bookworm should start without issues. External dependencies should not cause startup failure.

## Desktop (please complete the following information):

 - OS: Windows 11 21H2 (x64) build 22000.739
 - The issue also occurs when using Windows 10
 - Bookworm version 2022.1b1
 - Recent settings you may have changed in Bookworm: N/A

## Additional context
AccessibleOutput2 has not wittnessed any development efforts recently. Use another library that is being actively maintained. I propose [Cytolk](/pauliyobo/cytolk)

@pauliyobo  what do you think

**Comment by pauliyobo** [comment]
Hello, apologies for the delay.
I believe there is an updated fork of accessible output 2 [here](https://github.com/accessibleapps/accessible_output2)
Before we do anything we should perhaps investigate whether using that fork currently causes the same issue.
Can you verify it @mush42 ?
In any case, there is already a test branch that should contain a cytolk integration.

**Comment by TheQuinbox** [comment]
@mush42, if you pull Accessible_output2 from GitHub directly, like:
```shell
$ pip install github.com/accessibleApps/accessible_output2
```
this issue should be fixed. In [Pull Request 4](https://github.com/accessibleapps/accessible_output2/pull/4), this issue was fixed. Q just never bothered to push all the new changes to Pypi. AO2 has a lot of advantages over Tolk, because its cross-platform, supports more screen readers, etc.

**Comment by TheQuinbox** [comment]
Hi @mush42,
Christopher Toth has recently pushed the most recent accessible_output2 changes to Pypi. All should be good again! Simply bump the version
