### ISSUE TITLE
No search results when searching in a text document

### ISSUE THREAD

**Issue by DraganRatkovich** [blindpandas/bookworm#168]
## Describe the Problem

The title is mostly self-explanatory, but to be more precise, when opening a text document and doing a search with Ctrl + F, there are no search results and the window just stays on the search results, but it's empty.

## To Reproduce

1. Open Bookworm;
2. Open any text document, press ctrl+f to open the search box, type any word related to the content of the document, and press Enter.

You will notice that the search results window will be empty and will not change.

## Expected behavior

Bookworm should display results just like other formats.

## Desktop (please complete the following information):

 - OS: Windows 10 21H2
 - Bookworm version: Latest, downloaded from AppVeyor
 - Recent settings you may have changed in Bookworm: None

## Additional context

@mush42 This issue only affects the txt format, no other formats including pdf, epub, mobi or word are affected.

**Comment by cary-rowen** [comment]
yes, i can reproduce this
