### ISSUE TITLE
No search result in Word document

### ISSUE THREAD

**Issue by DraganRatkovich** [blindpandas/bookworm#172]
In order not to read for a long time, this problem arose when @pauliyobo fixed issue with txt search results. Now the same problem with Word document.
@pauliyobo Maybe you can contribute to this?

**Comment by pauliyobo** [comment]
Hello.
@DraganRatkovich were you able to search in word documents before #171 was merged?

**Comment by DraganRatkovich** [comment]
@pauliyobo Yes.
