### ISSUE TITLE
Remove dependency on .NET and pythonnet

### ISSUE THREAD

**Issue by mush42** [blindpandas/bookworm#190]
## Describe the Problem

One of the heaviest technical debts we must payback ASAP is the dependency on .NET to access SAPI5 and custom-built components related to one-core speech engine.

Using pythonnet prevents us from using alternative freezing solutions such as *Nuitka* or *pyOxidizer*

Additionally, maintaining components written in different languages and targeting different SDKs proved to be very tedious.

## To Reproduce

N/A

## Expected behavior

N/A

## If the problem is related to a file, indicate the file you have opened

N/A

## Desktop (please complete the following information):

 - OS: Windows (all versions)
 - Bookworm version 2022.1b1
 
## Additional context

The most appealing alternative is to use COM (via comTypes) when applicable, and rebuild remaining .NET dependencies in rust using the windows.rs crate.

To make this transition quicker, we can reuse some of NVDA's code.

**Comment by pauliyobo** [comment]
Hello @mush42 
Looks reasonable. Could probably be useful listing the dependencies and their status, in order to understand what is the progress.

**Comment by mush42** [comment]
Hello @pauliyobo 

The work on this issue is almost done. Check the sapi branch.

Currently working on fixing some rough corners and polishing the implementation.

**Comment by pauliyobo** [comment]
I'm going to close this, given that the sapi branch was already merged a while ago.
