### ISSUE TITLE
Enables Bookworm to follow system proxy

### ISSUE THREAD

**Issue by cary-rowen** [blindpandas/bookworm#191]
## Is your feature request related to a problem? Please describe.
Bookworm cannot currently follow the system proxy, and when I use V2RayN to enable the system proxy, Bookworm cannot download pandoc nor perform Wikipedia searches.
## Describe the solution you'd like
Enables Bookworm to follow system proxy
## Describe alternatives you've considered
None
## Additional context
None

**Comment by cary-rowen** [comment]
Hi, @mush42 
Do you have any thoughts on this? Will this be implemented?

**Comment by DraganRatkovich** [comment]
@pauliyobo Maybe you can contribute to this and #197, maybe Musharraf doesn't have time these days.

**Comment by cary-rowen** [comment]
Hi, @mush42 
The Issue seems to be fixed? is it?

**Comment by mush42** [comment]
Hi @cary-rowen 

On my part, I did nothing. Except upgrading to Python 3.10.
