### ISSUE TITLE
Updated Finnish UI messages and user guide

### ISSUE THREAD

**Issue by jkinnunen** [blindpandas/bookworm#192]
Here are the updated files:

[bookworm.po](https://www.dropbox.com/s/86h5qxk8aigbbwi/bookworm.po?dl=1)
[bookworm.md](https://www.dropbox.com/s/tg3d3h1aonei35e/bookworm.md?dl=1)

**Comment by DraganRatkovich** [comment]
@jkinnunen Please, open pull request instead of issue. We can merge PR to make updated locales available for everyone.

**Comment by mush42** [comment]
@DraganRatkovich 

I'll upload them manually.

Thanks

**Comment by DraganRatkovich** [comment]
@mush42 OK
