### ISSUE TITLE
Urgent help, all my Bookmarkss and notes disappeared after I switched to another reading mode in the PDF document

### ISSUE THREAD

**Issue by cary-rowen** [blindpandas/bookworm#202]
## Describe the Problem
I'm reading a PDF document in Bookworm, and I tried switching to the other two reading modes to see which one is friendlier.
But what I didn't expect was that when I switched back to the original reading mode, the original saved notes and bookmarks were lost.
## To Reproduce
1. Open a PDF and write some notes;
2. Press ctrl+shift+m,Switch to another reading mode;
3. Switch back to the original reading mode.
4. Notes no longer exist
## Expected behavior
User data such as original bookmarks and notes can still be found.
## If the problem is related to a file, indicate the file you have opened

Tell us what is the format of the file you've opened [e.g. PDF]. If possible, attach the file you have open in Bookworm when the problem happened.

## Desktop (please complete the following information):

 - OS: [Windows 10 22H2 (x64) build 19045.2251]
 - Bookworm version [Bookworm 2022.1b1]
 - Recent settings you may have changed in Bookworm [reading mode]

## Additional context
This might be a bug, but is there any way I can get my data back.

**Comment by mush42** [comment]
Hi @cary-rowen 

Sorry for any inconveniences.

I want to assure you that nothing is lost. Bookworm does not delete anything on it's own.

Your annotations are missing, because Bookworm now uses another identifier for the document. This is made because you may have different annotations for different reading modes.

**Comment by cary-rowen** [comment]
Hi @mush42
I used the sqlite tool to discover my saved notes, but is there a way for me to associate it with the original reading mode so I can use it again in Bookworm without having to re-create these notes manually.

**Comment by mush42** [comment]
@cary-rowen  I'm now working on a fix. It will be deployed in the next commit.

**Comment by mush42** [comment]
@cary-rowen  manually tampering with the database may cause a permanent lost of your data. I'll push the next commit within a few minutes.

**Comment by mush42** [comment]
@cary-rowen  please make sure to choose the default reading mode.

**Comment by cary-rowen** [comment]
@mush42 
Thanks for your hard work, this is what I want.
