### ISSUE TITLE
When adding notes please only target the selected text and not the entire line.

### ISSUE THREAD

**Issue by cary-rowen** [blindpandas/bookworm#205]
## Describe the Problem
I want to add notes to the selected text area (such as a specific term), but bookworm can only add notes to the entire line.
## To Reproduce

1. Open a document at random.
2. Select a part of any line.
3. Press Ctrl+M to write the note content and  save it.
4. Use the left or right arrows to view the line, you cannot see where the note start or end.
## Expected behavior
notes can be added to selected text, just like highlighting.
## If the problem is related to a file, indicate the file you have opened
None
## Desktop (please complete the following information):

 - OS: [Windows 10 22H2 (x64) build 19045.2251]
 - Bookworm version [2022.1B3]
 - Recent settings you may have changed in Bookworm [None]

## Additional context
None

**Comment by cary-rowen** [comment]
@mush42 

OK, looking forward to your good news.

Best
Cary

**Comment by cary-rowen** [comment]
Hi, @mush42   will this feature be difficult to implement?

**Comment by mush42** [comment]
I don't think it will be hard to implement.
I will try to work on it ASAP.
I'm a bit busy at work these days. Please be  patient with me.

**Comment by cary-rowen** [comment]
OK, thank you, my friend.
Anyway, please take care.

**Comment by cary-rowen** [comment]
Hi @mush42 
Any progress on this issue?

**Comment by cary-rowen** [comment]
cc @pauliyobo

**Comment by cary-rowen** [comment]
Thanks @pauliyobo
