### ISSUE TITLE
Error scanning pdf to text file using OCR

### ISSUE THREAD

**Issue by cary-rowen** [blindpandas/bookworm#208]
## Describe the Problem
Error scanning pdf to text file using OCR.
## To Reproduce

1. Download the provided file.
2. Open in bookworm.
3. Alt+O click on "Scan To Text File".
4. Using the default options, start the scan and you will receive the following error:
```
Failed to execute script 'Bookworm' due to unhandled exception: Error while finding loader for 'numpy' (<class 'ValueError'>: numpy.__spec__ is None)
```
## Expected behavior
The scanning process can be performed normally and this error should not occur.
## If the problem is related to a file, indicate the file you have opened
[test.zip](https://github.com/blindpandas/bookworm/files/10193743/test.zip)

## Desktop (please complete the following information):

 - OS: [Windows 10 22H2 (x64) build 19045.2251]
 - Bookworm version [2022.1Beta3]
 - Recent settings you may have changed in Bookworm [None]

## Additional context
The function to scan the current page works fine.

**Comment by pauliyobo** [comment]
@cary-rowen Sorry for the delay.
I was not able to actually reproduce the issue, is it still happening on your end?

**Comment by cary-rowen** [comment]
@pauliyobo 
No errors are encountered during the scan anymore, but I found a new error and bookworm cannot exit after the scan is completed.
I can create a new Issue if needed.

**Comment by pauliyobo** [comment]
@cary-rowen Please do. I'll be closing this then.
