### ISSUE TITLE
in the elements list dialog, the "Element Type" label isn't translated

### ISSUE THREAD

**Issue by jkinnunen** [blindpandas/bookworm#218]
## Describe the Problem

The "Element Type" grouping label isn't translated in the elements list dialog.

## To Reproduce

1. Start Bookworm and set its user interface's display language to some other than English.
2. Open a document by pressing Ctrl+O and then press Ctrl+F7 to open the elements list dialog.
3. The "Element Type" label isn't displayed in the configured language.

## Expected behavior

The "Element Type" label should be displayed in the configured language.

## Desktop (please complete the following information):

 - OS: Windows 11 22H2 (build 22621.1344)
 - Bookworm version: 2022.1b3 (1.0.441)

**Comment by cary-rowen** [comment]
Hasn't this been fixed by https://github.com/blindpandas/bookworm/commit/039611f9c7d39b0b6da685464d9962a9eaba60f4

**Comment by jkinnunen** [comment]
> Hasn't this been fixed by [039611f](https://github.com/blindpandas/bookworm/commit/039611f9c7d39b0b6da685464d9962a9eaba60f4)

Unfortunately not. Although the labels of heading, link, etc. are now translated, the element type label isn't.
