### ISSUE TITLE
feature request enable tts to save to mp3

### ISSUE THREAD

**Issue by mhussaincov93** [blindpandas/bookworm#223]
a nice to have, it would be great if the tts output could be converted in to a mp3.
you could use lame to do the encodeing.
or .wav files?
for very large ebooks split the .wav files in to 3.98gb files due to windows not likeing the 4gb .wav files.
I would be greatful if you would considder this as a request.
Majid

**Comment by pauliyobo** [comment]
I'm a bit on the fence on this. I feel somehow that this is out of scope for an ebook reader. But perhaps @mush42  or @cary-rowen have a different opinion?

**Comment by mush42** [comment]
@pauliyobo I agree this is out of scope for now.
