### ISSUE TITLE
An error was encountered while trying to prepare the build environment

### ISSUE THREAD

**Issue by cary-rowen** [blindpandas/bookworm#228]
## Describe the Problem
I'm trying to prepare a build environment for Bookworm locally, and I followed exactly the steps in the readme.
There is only one difference, the documentation mentions that we are using python3.9 but in fact we are already using python3.10.

## To Reproduce

1. clone this project
2. Install python3.10
3. Go to the bookworm directory and execute:
  - `python -m venv`
  - `.env\scripts\active`
  - `pip install invoke`
  - `invoke dev`
## actual behavior

  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'error'
  error: subprocess-exited-with-error

  Getting requirements to build wheel did not run successfully.
  exit code: 1

  [17 lines of output]
  Traceback (most recent call last):
    File "D:\git\bookworm\.env\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <
module>
      main()
    File "D:\git\bookworm\.env\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in m
ain
      json_out['return_val'] = hook(**hook_input['kwargs'])
    File "D:\git\bookworm\.env\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 118, in g
et_requires_for_build_wheel
      return hook(config_settings)
    File "C:\Users\cary\AppData\Local\Temp\pip-build-env-1gr9p9il\overlay\Lib\site-packages\setuptools\build_meta.py", l
ine 341, in get_requires_for_build_wheel
      return self._get_build_requires(config_settings, requirements=['wheel'])
    File "C:\Users\cary\AppData\Local\Temp\pip-build-env-1gr9p9il\overlay\Lib\site-packages\setuptools\build_meta.py", l
ine 323, in _get_build_requires
      self.run_setup()
    File "C:\Users\cary\AppData\Local\Temp\pip-build-env-1gr9p9il\overlay\Lib\site-packages\setuptools\build_meta.py", l
ine 487, in run_setup
      super(_BuildMetaLegacyBackend,
    File "C:\Users\cary\AppData\Local\Temp\pip-build-env-1gr9p9il\overlay\Lib\site-packages\setuptools\build_meta.py", l
ine 338, in run_setup
      exec(code, locals())
    File "<string>", line 6, in <module>
  UnicodeDecodeError: 'gbk' codec can't decode byte 0xa5 in position 623: illegal multibyte sequence
  [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

Getting requirements to build wheel did not run successfully.
exit code: 1

See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.

## Expected behavior
The source tree can be prepared as expected

## If the problem is related to a file, indicate the file you have opened

Tell us what is the format of the file you've opened [e.g. PDF]. If possible, attach the file you have open in Bookworm when the problem happened.

## Desktop (please complete the following information):

 - OS: [e.g. Windows 10 64-bit]
 - Bookworm version [e.g. 0.1.0b1]
 - Recent settings you may have changed in Bookworm [e.g. changed the speech settings]

**Comment by mush42** [comment]
Hi @cary-rowen 

Try setting the following command before you install `invoke`:

```cmd
set PYTHONIOENCODING=utf-8
```

Probably the issue is related to the character encoding of your terminal.

Best
Musharraf

**Comment by pauliyobo** [comment]
@cary-rowen Hello.
Does the problem still persist? If yes, would you mind trying the latest build whenever it completes?
Thank you.

**Comment by pauliyobo** [comment]
@cary-rowen hello,
What do you get if you run the following command?

```
python -c "import sys;print(sys.getdefaultencoding())"
```

**Comment by cary-rowen** [comment]
Hi @pauliyobo 
> What do you get if you run the following command?
> python -c "import sys;print(sys.getdefaultencoding())"
I get: utf-8
