### ISSUE TITLE
Bookworm does not split some lines

### ISSUE THREAD

**Issue by k-kolev1985** [blindpandas/bookworm#24]
## Describe the Problem

In the book that I'm currently reading, I've noticed that Bookworm does not split a particular text into separate lines as it should. When I load the book into Microsoft Edge or Balabolka, the text is properly split into separate lines. The lines in question are verses in a poem. It seams that the whole poem is combined in a paragraph.

## To Reproduce

1. Launch Bookworm.
2. Open a book containing poem(s) with verses. I can provide a book, but it is in bulgarian.
3. Check how the lines in the verses of the poem(s) are combined in a single paragraph.

## Expected behavior

Bookworm should split correctly lines of verses in a poem.

## The File You've Opened

The file with which I've noticed this is a EPUB.

## Desktop (please complete the following information):

 - Operating system: Windows 10 Pro version 1903 (build 18362.388), 64-bit, in Bulgarian with all locale settings set to "Bulgarian".
 - Bookworm version: 0.1b3, x86 (32-bit).

**Comment by mush42** [comment]
Hi @k-kolev1985 ,

I'm aware of such issues my self when reading books in Arabic. Text extraction from EPUB documents needs rewriting.
It is possible to get 100% accurate text extraction, but it implies that we forego the visual rendering of the eBook.
What do you think?

**Comment by k-kolev1985** [comment]
Hi @mush42 

Am I understanding you correctly, that, at least for the time being, in order to achieve 100% accuracy in EPUB text extraction, the visual rendering of the book must be sacrificed/will not work? If so, from my current point of view, that is not a problem, since due to issue #9 it does not work properly for me anyway (smile).

**Comment by AntonioCezar** [comment]
Hi. In my case it is different because the Bookworm creates some line breaks nonexistent in the text, and I'm sure this does not result from converting an EPUB file, because I converted my Monograph in brasilian portuguese directly to PDF using MS Word 2016 and when I use Bookworm for reading it, some line breaks artificially introduced by the Bookworm are there, but when I open the file in some other PDF readers, or even to convert txt, line breaks no longer appear... Thanks.

**Comment by zersiax** [comment]
I'd say that the render mode will do for the visual aspect of things, whereas the plain text view can probably divert from the visual representation of the book. I see both issues; the one where code is all on one line (probably a <pre> tag) and longer lines that are split into shorter lines by Bookworm, but not by other readers such as https://loudreader.com.
I love the annotation and bookmarking features of this app and would be elated if the text render was more in line with what i'm seeing from the above.
