### ISSUE TITLE
Request update bookworm

### ISSUE THREAD

**Issue by cary-rowen** [blindpandas/bookworm#241]
1. Bookworm is currently unable to download the latest build because the last submitted build failed.
2. The version of Bookworm needs to be updated. The latest build version number is still 2022.1.
3. Bookworms If you need to donate I will be happy to support, I wrote an email to the main developer at the beginning of the year hoping to hear more about donations.
4. I’m not sure if I heard at a certain moment: The main developer has implemented some new features, but due to the war, it cannot be pushed. If so, I'd love to know how you're doing right now?
5. There are several important issues that I think urgently need to be fixed. They are: #205, #210 and #229.

cc @mush42

**Comment by cary-rowen** [comment]
cc @pauliyobo @mush42 
What are your plans for this?

**Comment by luzpaz** [comment]
bump

**Comment by pauliyobo** [comment]
Hello, I apologize for the delay from my side.
Personally, I'm a bit conflicted on how to proceed, but I'll try to answer from my perspective.

> 1. Bookworm is currently unable to download the latest build because the last submitted build failed.

Regarding this, In #234 we switched from Appveyor CI to GH actions, which should make this problem a bit more bearable. 

> 2. The version of Bookworm needs to be updated. The latest build version number is still 2022.1.

Correct, a version bump would be in order.

> 3. Bookworms If you need to donate I will be happy to support, I wrote an email to the main developer at the beginning of the year hoping to hear more about donations.

I can't really answer to this as I am really no more than a collaborator, so @mush42 would have to get back to you when he is able.

> 4. I’m not sure if I heard at a certain moment: The main developer has implemented some new features, but due to the war, it cannot be pushed. If so, I'd love to know how you're doing right now?

Hmm, I do believe some were already merged in the codebase, such as the ability to choose Espeak as an engine to read documents aloud.

> 5. There are several important issues that I think urgently need to be fixed. They are: When adding notes please only target the selected text and not the entire line. #205, Reading position cannot be saved in documents of some formats #210 and Comments and notes are lost after changing the save location of the document #229.

Yes, that's also correct, I'll try to tackle them as time allows.

We might have enough material to at least probably plan a release, though I would rather prefer @mush42's input since ultimately he's the project lead and as such he might have other plans. Until then though I agree the outstanding issues should be addressed.

**Comment by cary-rowen** [comment]
Thanks @pauliyobo

I also have some code for bug fixes that I'd like to contribute to the project, but I don't currently see @mush42's plans on the project.
What confuses me even more is that @mush42 seems to be active on other projects.


cc @mush42 
Do you have any plans for Bookworm that you can share?

Best,
Cary

**Comment by amirsol81** [comment]
@mush42 @pauliyobo @cary-rowen What happened to the project and the bugs discussed here? In particular, bugs #205 #210 and #229 ? Also will DAISY support and Bookshare downloading be implemented? This is a bit saddening, but the project is either dead or very slow to address bugs and add new features. I see some commits made last months, but when will be translated into user-noticeable fixes and features?

**Comment by RuturajL** [comment]
Oh, if they implement Bookshare integration, this would be game-changer.
I think all of us here would agree that Bookshare integration is a very highly needed feature.
Small additions I would like to raise in a new issue if they are already not raised inclued Bookworm unable to display tables in accessible format, and, may be accessible math  support if that's already not implemented.

**Comment by cary-rowen** [comment]
Regarding support for math content, there is already an Issue #162
Bookshare, Table nav New feature requests are welcome.

**Comment by pauliyobo** [comment]
Hello.
Yeah, I believe there are some features that would likely make the experience better over all.
Currently though I believe  there are some long standing issues that have to be addressed, as you've all rightfully pointed out.
Though before that we'd probably be better off to migrate some dependencies, such as sqlalchemy, which is still on version 1.x.

**Comment by cary-rowen** [comment]
Hi @pauliyobo 
According to the communication between @mush42 and me, we are leaning towards launching a new version in the near future, do you think some dependencies need to be upgraded before launching the new version? Are you willing to complete this?
For example, upgrade sqlalchemy to a newer version

**Comment by cary-rowen** [comment]
We have released [2024.2](https://github.com/blindpandas/bookworm/releases/tag/2024.2) and now I will close this.
