### ISSUE TITLE
Bookworm cannot exit after scaning pdf 

### ISSUE THREAD

**Issue by cary-rowen** [blindpandas/bookworm#242]
## Describe the Problem
Can't exit after scanning pdf
## To Reproduce

1. Download the provided file.
2. Open in bookworm.
3. Alt+O click on "Scan To Text File".
4. Using the default options, start the scan.
5. Once the scan is complete try exiting bookworm from the menu.
## Expected behavior
You can exit the software normally after scanning and this error should not occur.
## If the problem is related to a file, indicate the file you have opened
[test.zip](https://github.com/blindpandas/bookworm/files/10193743/test.zip)

## Desktop (please complete the following information):

 - OS: [Windows 10 22H2 (x64) build 19045.2251]
 - Bookworm version [2022.1Beta3]
 - Recent settings you may have changed in Bookworm [None]

## Additional context
The function to scan the current page works fine.
Can't exit after scanning pdf

**Comment by pauliyobo** [comment]
Hello
@cary-rowen I appear to be unable to reproduce the issue.
Did you encounter any traceback?
