### ISSUE TITLE
Wrong chapter order when reading epub file (chapter 29, chapter 3, chapter 30.

### ISSUE THREAD

**Issue by ogomez92** [blindpandas/bookworm#243]
## Describe the Problem
I was reading a book and I was on chapter 29, then chapter 3 came up, then chapter 30.
I will provide more details in how to reproduce

## To Reproduce
Open the linked file in this issue.
Go to reading percentage 69, you will be at the end of chapter 29. Alternatively use H and shift H to jump via headings.

You will notice that if you press down arrow at this point you will be on chapter 3 instead of chapter 30.
At the end of chapter 3, chapter 30 comes up.
It seems as though it's getting the wrong order, as in a Mac or Unix like environment instead of windows, because chapter is not 03, but just number 3.

## Expected behavior

Read in the correct chapter order.

## If the problem is related to a file, indicate the file you have opened

https://drive.oriolgomez.com/f/4ec6e05626d34198a7b7/

## Desktop (please complete the following information):

Windows 11, Spanish localization.
Bookworm latest version (no updates found).
 - Recent settings you may have changed in Bookworm [e.g. changed the speech settings]: None

**Comment by pauliyobo** [comment]
Hello. Thank you for opening the issue.
Would you be able to provide the file again? The link seems to be unavailable.

**Comment by ogomez92** [comment]
Sorry about that:
https://drive.oriolgomez.com/f/b68e57a03cb546d7bb0e/

I have also noticed that it happens with chapters 1 and 10, 11 and 20, and so on.

It seems to have the wrong Unix order.

Also investigating this further, the table of contents has the right order, and other applications read this file correctly.

Thanks.

**Comment by pauliyobo** [comment]
Hello. I am unable to reproduce this issue.
Are you trying from the latest release or from the latest build?

**Comment by ogomez92** [comment]
I was trying from the latest release. Not the latest build. Maybe something
changed between the latest release and build?

**Comment by pauliyobo** [comment]
Weirdly enough I can't seem to reproduce it even from the version provided in the website.
I wonder if localization may have a factor in this.

**Comment by ogomez92** [comment]
Possibly.
I'm using the Spanish (Spain) regional settings.

**Comment by cary-rowen** [comment]
I'm currently unable to get the files for testing. You can simply change the book file to a .zip extension and upload it on github.

**Comment by ogomez92** [comment]
I found yet another file where it happens, but this time with roman
numerals.
It goes from I, II, III, IV, and then IX, then V (I'm guessing because of
IV and then IX).

It seems to be the same issue.

https://www.oriolgomez.com/files/roman.epub

**Comment by pauliyobo** [comment]
Yeah, I can reproduce this too, on the latest build.

**Comment by pauliyobo** [comment]
Apologize for the double comment.
On further notice, it looks like the TOC is ordered properly.

**Comment by cary-rowen** [comment]
Hi @pauliyobo

It looks like this bug is not fully resolved and I have another Epub ebook that reproduces this.
Below are the books I'm having trouble with.
Please remove the .zip extension after it has been restored to epub file.

**Comment by cary-rowen** [comment]
[testFile](https://dl.nvdacn.com/GuestUpload/3e61cef854eb6836d406a0f8d052f9d1.zip)
