### ISSUE TITLE
Associated files affect menu items in the "New" menu

### ISSUE THREAD

**Issue by cary-rowen** [blindpandas/bookworm#247]
## Describe the Problem

Associating files with Bookworm affects the items in the "New" menu of the right-click context menu.

## Steps to Reproduce

1. Open Bookworm Preferences → General → Manage File Associations.
2. Associate Bookworm with .rar, .zip, and .txt file extensions.
3. Go to the desktop, press Ctrl+Alt+Space, then press the Applications key and press the W key.

## Expected Behavior

The .rar, .zip, and .txt file extensions in the menu items should all use the file type descriptions from Bookworm. More importantly, if Bookworm is uninstalled, these menu items will disappear, and users will not be able to create .txt documents, .zip, and .rar files.

## File-Related Information

n/a

## Desktop Information

- OS: Windows 10 22H2 (AMD64) build 19045.3930
- Bookworm version: Latest build
- Recent settings changed in Bookworm: File association

## Additional Context

When Bookworm associates a file type, it creates entries in the registry at the following path:

`HKEY_CURRENT_USER\SOFTWARE\Classes`

For example: `HKEY_CURRENT_USER\SOFTWARE\Classes\.txt`

The above registry key will overwrite `HKEY_CLASSES_ROOT\.txt`

When canceling the file association, Bookworm will not delete the `.txt` entry located under `HKEY_CURRENT_USER\SOFTWARE\Classes` but will delete its subkeys. This is what causes some menu items to be missing from the "New" menu.

However, I have some doubts. Can we directly delete the `.txt` entry under `HKEY_CURRENT_USER\SOFTWARE\Classes`? I confirm that this does not exist by default. But if deleted, will it affect other application associations?

**Comment by cary-rowen** [comment]
cc @mush42 @pauliyobo

**Comment by pauliyobo** [comment]
Hello.
So sorry for the delay in my responses.
I understand the problem. I guess it's probably more reliable to actually bake this functionality in the installer itself since at that point, when uninstalling it would remove  the registry entries on its own.

**Comment by cary-rowen** [comment]
I think the most important issue here is that file associations affect the "new" menu.
Especially for .zip and .rar files. In this case, the .rar and .zip menu items in the New menu use bookworm's file type description.
