### ISSUE TITLE
Feature request: Allow users to individually unassociate associated file types and display association status on the button for each associated file

### ISSUE THREAD

**Issue by cary-rowen** [blindpandas/bookworm#255]
## Is your feature request related to a problem? Please describe.
Currently, users can associate a certain file type with bookworm, but they can only cancel the association in batches, and users do not know which files have been associated with bookworm.
## Describe the solution you'd like
* Allows users to individually unassociate a file type.
* If a certain type is associated, its status is displayed on the corresponding button, indicating that the association can be cancelled.
## Describe alternatives you've considered
None
## Additional context
I will consider implementing it when I have time, you can assign it to me.

**Comment by mush42** [comment]
@cary-rowen  Well done 👏
