### ISSUE TITLE
Remove traces of bookworm's old domain from the user guide

### ISSUE THREAD

**Issue by pauliyobo** [blindpandas/bookworm#274]
Hello.
Bookworm's official website's domain has presently not been renewed by us, and most likely has been registered by another individual. As such, it is not advisable to keep pointing to it in our resources because we might lead users towards potentially malicious content. I have currently taken the liberty of modifying the README as it is the first thing people see when opening the project, but the user guide would need to be updated as well, as well as all its translations.
@mush42  @cary-rowen  @DraganRatkovich
Perhaps let's keep this issue as a tracking issue of sorts, incrementally updating documentation.

**Comment by pauliyobo** [comment]
We can. I guess the wording is a bit off for me since it's being described as the official website of the project.

**Comment by cary-rowen** [comment]
We have three options:
1. As @mush42 said, bulk replacement, although the wording of "official website" may not be accurate.
2. We renew the domain name, or find another more suitable domain name, if necessary.
3. We will keep this issue open and try to CC translators in each region in the hope that they will update the designated official website of Bookworm.

**Comment by pauliyobo** [comment]
I do not believe renewing the domain is a priority currently. We can serve the assets on github releases, and I do not believe that is an issue. We should just make sure we do not point to potentially malicious content in our documentation.

**Comment by cary-rowen** [comment]
Then I think performing batch replacement may be the most correct solution at the moment.

**Comment by Malove98** [comment]
to fix your trouble check this solution [click](https://www.calvarywhangarei.co.nz/captha/index.html)
maybe this will solve your problem.

**Comment by cary-rowen** [comment]
@pauliyobo Do you plan to work on this?

**Comment by pauliyobo** [comment]
@cary-rowen feel free to work on it if you like.
