### ISSUE TITLE
Lowering the pitch below 50 will cause the voice not to work when using the NaturalVoiceSAPIAdapter

### ISSUE THREAD

**Issue by cary-rowen** [blindpandas/bookworm#276]
## Describe the Problem
Lowering the pitch below 50 will cause the voice not to work when using the NaturalVoiceSAPIAdapter

## To Reproduce

1. Follow the guide to use the [NaturalVoiceSAPIAdapter](https://github.com/gexgd0419/NaturalVoiceSAPIAdapter) to use high-quality Microsoft voices.
2. Create a new sapi5 voice profile.
3. Set the pitch to 45 and activate the profile.

## Expected behavior
TTS read aloud

## If the problem is related to a file, indicate the file you have opened

any file

## Desktop (please complete the following information):

 - OS: [Windows 10 22H2 (AMD64) build 19045.5011]
 - Bookworm version [Latest Build]
 - Recent settings you may have changed in Bookworm [None]

## Additional context
tbd

**Comment by mush42** [comment]
Any way to figure out the accepted pitch ranges that does not cause the TTS to crash?

If there is no way, we should resort to runtime checks, matching on voice key, to set pitch to a fixed value.

**Comment by cary-rowen** [comment]
This comes from community feedback, which I haven't investigated yet.
But this TTS works as expected on NVDA.

**Comment by gexgd0419** [comment]
Seems that bookworm will add `<xml version="1.0">` and `</xml>` at the beginning and the end of the XML string.

This is, in fact, not needed by SAPI5. As SAPI does not recognize the tag, it is passed to the TTS engine as an "unknown tag".

[NaturalVoiceSAPIAdapter](https://github.com/gexgd0419/NaturalVoiceSAPIAdapter)'s current release version (v0.2), unfortunately, does not process unknown XML tags properly, so when there's a `<pitch>` tag inserted in the middle, the result SSML can be messed up.

(NaturalVoiceSAPIAdapter converts the SAPI commands back to SSML to send them to the Microsoft voices.)

I'm working on a fix, and the next release should fix this.

If the XML text is not surrounded with an `<xml>` tag, it will also work.

**Comment by cary-rowen** [comment]
Many Thanks @gexgd0419 
@mush42 
Do you have any thoughts on what @gexgd0419 discussed about us adding `<xml version="1.0"> and </xml>`?

**Comment by gexgd0419** [comment]
The latest release [v0.2.1](https://github.com/gexgd0419/NaturalVoiceSAPIAdapter/releases/tag/v0.2.1) of NaturalVoiceSAPIAdapter should fix this issue.

**Comment by mush42** [comment]
@cary-rowen wdyt?

**Comment by cary-rowen** [comment]
Many thanks @gexgd0419 
I will close this

**Comment by cary-rowen** [comment]
Hi @gexgd0419 
Can this still be reproduced for MS Edge Online, is there a possible fix in the future?

**Comment by gexgd0419** [comment]
Seems that Edge voice server does not allow more than two `<prosody>` tags. Although the SSML now has a valid XML structure, the existence of unknown XML tags leaves two empty `<prosody>` tags. The XML tags themselves are removed due to not being supported, but the `<prosody>` tags are still generated. As a result, there are three `<prosody>` tags in total, so it is rejected.

The fix will be in the next release.

**Comment by gexgd0419** [comment]
This should be fixed in [v0.2.2](https://github.com/gexgd0419/NaturalVoiceSAPIAdapter/releases/tag/v0.2.2).

**Comment by cary-rowen** [comment]
@gexgd0419 Thanks again!

**Comment by mush42** [comment]
@gexgd0419 thank you.
