### ISSUE TITLE
Adding Spanish translation

### ISSUE THREAD

**Issue by ericdq** [blindpandas/bookworm#281]
hello, I have received the updated Spanish translation. I include the .mo file compressed in .zim. It should be in the following path:
bookworm\bookworm\resources\locale\es\LC_MESSAGES

**Comment by cary-rowen** [comment]
cc @ericdq

**Comment by cary-rowen** [comment]
Thanks @ericdq 

I noticed that you submitted the document in .md, can you also include the interface translation of bookworm, it should be a .po file, no .mo file is required.

BTW, you can also update the PR description. Link the PR to the issue using 'fix#281'

**Comment by ericdq** [comment]
fact. I think everything is now correct.
