### ISSUE TITLE
Document cache is loaded even after a document is updated

### ISSUE THREAD

**Issue by danielw97** [blindpandas/bookworm#288]
## Describe the Problem

Currently, the document cache is used to speed up the loading of documents I assume.
However, at the moment when a document such as an epub is updated i.e. with a new chapter for instance and it's name isn't changed the document is always loaded from the cache as apposed to the file size/modification time being checked as an example.

## To Reproduce

1. load an epub initially, so that it can be cached.
2. I'm using a utility called fanficfare that updates epubs with new chapters, so that is my example in this case.
3. Update the epub with new chapters via fanficfare, and try to reopen the document in bookworm.
4. observe that the version of the file from the cache is displayed, as apposed to the updated one.

## Expected behavior

Bookworm should recognize that the local version of the file is newer and update the cached copy.

## If the problem is related to a file, indicate the file you have opened

epub, see above.

## Desktop (please complete the following information):

 - OS: Windows 11 64-bit
 - Bookworm version: 2024.2
 - Recent settings you may have changed in Bookworm: n/a

## Additional context

It would be excellent if this problem could be looked at at some point, as I assume this affects other users also.
if there's any testing/more info I can provide, please do let me know.

**Comment by danielw97** [comment]
@pauliyobo thanks for the quick fix.
A quick test from your pr seems to resolve the problem, thanks again for fixing this so quickly!
If there's any more feedback you need on this do let me know.

**Comment by pauliyobo** [comment]
Hello.
Thank you. I will go ahead and close the issue then.
