### ISSUE TITLE
unable to access links in epub files 

### ISSUE THREAD

**Issue by a-singer** [blindpandas/bookworm#4]
Hello,

Many Epub files have footnotes and endnotes which are linked to from within the text. This is very common, and very helpful, in academic texts, but is also very useful in other texts. Often readers will have these listed in their notes area but I notice that BW doesn't seem to acknowledge these links. It would be most helpful for the program to support such links. I am pleased to send, if needed, a copy of a text with plenty of these notes.

Thanks,

**Comment by zersiax** [comment]
Was this ever added? I don't see a hotkey to access the links in the manual from the stable version I grabbed off the website. Links are announced, though.
