### ISSUE TITLE
Issues and suggestions

### ISSUE THREAD

**Issue by Kedi13** [blindpandas/bookworm#41]
# the issues  

* Even in correctly labelled files, NVDA voice won't change to the correct language, i.e, I opened a book in English and was quite confused that the voice remaining my standard Portuguese one. When reading with the voices installed on windows, the voices are changed accordingly though.  
* When using continuous reading, NVDA will read the page number every time it turns. As useful as it might be, it is slightly annoying.  
* It isn't possible to focus the note title with the common tab / shift tab keys.

# The suggestions
* add a shortcut to hide / show the table of contents.  
* Add a library interface, where the user could create and manage shelves. This would be specially handy for students and anyone who likes organizing their content.  
* Add the possibility to choose which voice will be used for each language.  
* Make it possible to know which section of the text was notated. It can be done by adding the desired text to the note title, but it might be interesting to do it automatically when you create a note.  

# Conclusion
I'm very pleased to see that there is a modern and powerful E Book reader being developed. Please keep this one going.

**Comment by mohdshara** [comment]
Wouldn't it have been easier for the developers and everyone if those problems / suggestions were posted as individual issues?
Thanks.

**Comment by mush42** [comment]
Hello @Kedi13 

As @mohdshara  said; it would be much better if you move each one of those issues and suggestions to it's own issue. This will make it easier to track their progress, specially as some of those issues have been implemented already.

Best
Musharraf
