### ISSUE TITLE
Text display issues

### ISSUE THREAD

**Issue by snufas** [blindpandas/bookworm#43]
## about the problem ##

Hi, thank you for such amazing app.
The app is great, however the format of the epub and pdf  files  is not displayed correctly. It is particularly problematic where I'm trying to read the code, I will provide the example below to illustrate the problem.

## Actual Behavior
I have the following line below copied from the epub book that is about coding
quick note, the line below is rendered as one line of code

#mainCanvas {    width: 400px;    height: 400px;    border: solid 1px black; }
this happens when I open pdf or epub book in this app.

## Expected Behavior

same line of code should be rendered as follows

#mainCanvas {    
	width: 400px;    
	height: 400px;    
	border: solid 1px black; 
}

I checked how it's supposed to be rendered against same pdf file in adobe acrobat.

I'm assuming that the coder who wrote the app should be aware about need to read code correctly using screenreader 
I hope it could be fixed, because it is a great option. To read books, knowing the fact that PDF books are not always accessible it is great alternative to read any book in accessible way.

Thank you for such amazing app, and best of luck in future development, also high contrast mode is a must without a doubt.

### Bookworm Version:
version: 0.1b4
### Windows Version:
2020-04

## Does the issue still occur after restarting your PC?
yes
## Have you tried any other versions of Bookworm? If so, please report their behaviors.
nope

**Comment by mush42** [comment]
Thanks. Issue noted.
Currently I'm undertaking a massive refactoring effort. Hopefully this issue will be fixed as a result.

**Comment by snufas** [comment]
thanks for your hard work @mush42  it is eazy to use, but the only thing that is needed is the proper format rendering.  i hope your software wil be the my daly driver for learning how to code, as i said pdfs are not  accesible, well they are but the coding part is not if the pdf is not formatted correctly.

**Comment by snufas** [comment]
@mush42 
Are you getting any closer to fix the formatting issue? I have the latest version and the issue still exists. 
My logic tells me that you are not registering the return key character in text to register a new line, once again I will illustrate the issue with the example below.

Original layout from PDF:

portfolio = [
{'name': 'IBM', 'shares': 100, 'price': 91.1},
{'name': 'AAPL', 'shares': 50, 'price': 543.22},
{'name': 'FB', 'shares': 200, 'price': 21.09},
{'name': 'HPQ', 'shares': 35, 'price': 31.75},
{'name': 'YHOO', 'shares': 45, 'price': 16.35},
{'name': 'ACME', 'shares': 75, 'price': 115.65}
]

Same information displayed in the bookworm 

portfolio = [    {'name': 'IBM', 'shares': 100, 'price': 91.1},    {'name': 'AAPL', 'shares': 50, 'price': 543.22},    {'name': 'FB', 'shares': 200, 'price': 21.09},    {'name': 'HPQ', 'shares': 35, 'price': 31.75},    {'name': 'YHOO', 'shares': 45, 'price': 16.35},    {'name': 'ACME', 'shares': 75, 'price': 115.65} ]


So the problem is clear enough to me, it seems that this app does not take the return character into consideration, because from the example above is clear where the problem is,. 
It would be amazing to fix such problems, because formatting issues are the real deal for screenreader users.
Personally I think that would be the number 1 bug to fix, reason being that it does not display the text correctly which makes much harder to read the books particularly related to coding.

This bug solved and dark mode, that's all I would need to consider this app a perfect replacement for any other reading software for my needs.
Thanks again for such amazing work.

**Comment by mush42** [comment]
Hi @snufas ,

Give me some time to investigate this issue.

**Comment by snufas** [comment]
@mush42 

yep np at all, does not matter how long it takes but please try to get rid of this  issue.

Thannks

**Comment by mush42** [comment]
Hi all,

The text extraction issue has been fixed for PDF documents by the introduction of the reading modes feature.
It remains to be fixed for EPUB documents. And it is a matter of time.

Thanks,

**Comment by snufas** [comment]
@mush42 
That's great news, so I will wait for EPUP support then, I was just about to make a podcast about reading the EPUB files using Thorium.
It works quite well, it is not as simplistic though as your app is. Thanks for your great work again. Do you know how long it will take to you to make EPUB work properly? 
Because I want to inform my readers about this change, and I think it's really important to have accessible e-book reader.

I have a suspicion that not many people do know about this 1, I think once the formatting issues are fixed it's worth spreading the word.
I would not mind to talk about this on my podcast with you, I am not sure if you would agree with that, if you would however, please let me know in the comment.

Website: techvb.net you can check it out for yourself, and see whether you like the content there, if that helps you to decide.
