### ISSUE TITLE
hope Bookworm can display the images in the e-book

### ISSUE THREAD

**Issue by cary-rowen** [blindpandas/bookworm#44]
## Is your feature request related to a problem? Please describe.
As described in the titleMany e-books contain images, Although most of us don't know what's in the image, But that doesn't mean it's useless.
Bookworm is a good software, if it already has this function, please let me know and please to close the issue
## Describe the solution you'd like
Be able to display images on the screen in an appropriate way.
## Describe alternatives you've considered
I didn't think of an alternative for the time being. Displaying images is necessary.
## Additional context
1. Ask others to describe the image content in the book.
2. I believe that visual users would like to have this feature more.

**Comment by mush42** [comment]
We have a similar feature in terms of Rendering the pages, images included.
Adding a separate view for page images may prove useful for some users. So, I'm keeping this open for now.

**Comment by man0528** [comment]
Thank you for your reply.
I will provide localized translation of simplified Chinese for BW.

**Comment by mush42** [comment]
@man0528 please provide me with your email address. Send it to my email. You can find my email in the About Bookworm dialog in the Bookworm application.

**Comment by cary-rowen** [comment]
oh, The web Viewer seemed to solve this, so I close it.

**Comment by mush42** [comment]
Thanks @cary-rowen 
Always glad to help.
