### ISSUE TITLE
Bookworm Beta reads twice the last page of a book

### ISSUE THREAD

**Issue by k-kolev1985** [blindpandas/bookworm#52]
## Problem description

I've noticed that Bookworm Beta reads twice the last page of a book when reading on its own (not via the screen reader). I have a lot of e-books in EPUB format downloaded from a local (bulgarian) public site for e-books. Each e-book there has a single-page section in its end, called "Credits". When Bookworm reads on its own (with F5) and reaches that last single-page section called "Credits", it reads it twice. I was able to reproduce this only with SAPI5, but not with OneCore. Since the books are in bulgarian, I was able to test only with one SAPI5 bulgarian voice - "Irina" from "Innoetics", because the other one - "SpeechLab Gergana" seams not to be compatible with Bookworm (for reference - see [Bookworm issue #31 - Bookworm does not correctly initialize a specific bulgarian SAPI5 TTS voice](https://github.com/blindpandas/bookworm/issues/31). Therefore, I can't tell for sure if the problem is in Bookworm or the voice. Additionally, now I've tested with an e-book in EPUB format in english with the SAPI5 variant of the english voice "Microsoft David" and the issue was also reproducible. So, it is not due to a specific book or a specific TTS voice.

## Steps to reproduce it

1. Open Bookworm.
2. In Bookworm's preferences, from the "Voice" section, select the SAPI5 engine and then the bulgarian voice "Irina".
3. Open a book in it. Preferably the example one that I'll attach here.
4. Go to its last page and then go 1 page back.
5. Press F5 to read that page and the next/last page of the book.

## Expected behavior

Bookworm should read the last page of the book only once, as does the stable release of the program.

## Actual behavior

Bookworm reads the last page of the book twice.

## The File You've Opened

The book formats that I read in are EPUB ones. I don't know if the problem is reproducible with other supported e-book formats. I'll attach an example e-book in EPUB format. It is in bulgarian, but for the purposes of the testing, I think this does not matter.

## Test environment

 - Operating system: Windows 10 Pro version 2004 (build 19041.572), 64-bit, in Bulgarian with all locale settings set to "Bulgarian".
 - Bookworm version: 0.2a4, portable, in english.
 - Processor: Intel Core i5-9400F at 2.90GHz.
 - RAM Memory: 16.00GB.
 - Graphics: MSI GeForce GTX-1050TI Gaming X 4G, 4096MB dedicated memory, desktop resolution set to 1920x1080.
 - Sound Card: Realtek ALC892 at Intel Cannon Point PCH.

## Additional context

Here is the example e-book in EPUB format, zipped:

[TestBook.zip](https://github.com/blindpandas/bookworm/files/5400319/TestBook.zip)

**Comment by cary-rowen** [comment]
Hi @k-kolev1985 
Can you reproduce the issue with the latest version?
Thanks

**Comment by k-kolev1985** [comment]
No, I can't reproduce the issue with version 2022.1a5 of Bookworm.

**Comment by cary-rowen** [comment]
Hi @k-kolev1985 @mush42 
It seems that the issue has been resolved, you can close this.
Thanks

**Comment by mush42** [comment]
Thanks @k-kolev1985   @cary-rowen
