### ISSUE TITLE
Stable and alpha versions of Bookworm show different number of pages for the same book

### ISSUE THREAD

**Issue by k-kolev1985** [blindpandas/bookworm#54]
## Describe the Problem
While reading books and testing the current alpha version of Bookworm, I've noticed that it and the stable release show the same book with different number of pages. I've noticed this with EPUB files. For example, the same book in the stable release of Bookworm is displayed with 397 pages and in the current alpha is displayed with 430 pages. In all cases the number of pages is bigger in the alpha version than it is in the stable one.

## Steps to Reproduce it
1. Open the stable release of Bookworm.
2. Load a book in EPUB format in it (preferably one with more pages, e.g. one with a few hundred pages).
3. Check how many pages does the book have, by opening the "Go to page" dialog of Bookworm.
4. Open the alpha release of Bookworm.
5. Load the same book from step 2.
6. Check how many pages does the book have, by opening the "Go to page" dialog of Bookworm.

## Expected behavior
The number of pages should be the same, considering that the book is the same in both cases.

## Actual behavior
The number of pages is different - the alpha version of Bookworm shows it with more pages.

## The File You've Opened

The problem occurs at least with EPUB files. I don't have other e-book formats to test it with. I've tried with several books/files and the problem occurs with all of them.

## Desktop (please complete the following information):

 - Operating system: Windows 10 Pro version 20H2 (build 19042.746), 64-bit, in Bulgarian with all locale settings set to "Bulgarian".
 - Bookworm version: 0.2a4

**Comment by mush42** [comment]
Hi @k-kolev1985,
Thanks for reporting this.
This bug is critical as it effects saved notes and bookmarks.

Most likely the library we use to extract text out of EPUBs changed it pagination algorithm. Let me check that.

**Comment by mush42** [comment]
Hi @k-kolev1985 

Please note that splitting an EPUB document to pages is now done based on the structure of the book. For instance, each chapter or section is now represented as a single page. This is considered an appropriate way to deal with EPUBs due to their fluid nature.

In Bookworm v0.4 and later versions, as long as you're providing the same EPUB file, you will get the same page structure.

I can bring back the original mode of pagination (as provided in previous versions) as an alternative reading mode for EPUBs if desired, but the structured navigation will not be available with that mode.

Regards,

**Comment by k-kolev1985** [comment]
Yes, after posting my report about this a few days ago, I realized how EPUB pagination works in Bookworm 0.4. It creates a new page only when a new section or chapter begins. I realized this based on my observations while reading a book. 😀

As for providing the old pagination mode as an alternative reading mode. I think it is a good idea, even if it will not support structured navigation as the new pagination mode does. Personally I don't care much one way or another. But you can't imagine how many times blind users have asked me why Balabolka for example does not indicate book pages, considering that MS Word does that for the same file. The funny thing is, that they've been asking this for the TXT file format, which as you probably know, does not support pages. 😀 It's just that in some of its viewing modes MS Word does split even TXT files into pages and the blind thought that it is based on the real/scanned book and not just based on default text and page style used for TXT files in MS Word. You don't know how many times I had to explain that TXT files do not have support for pages as for example DOC files do.

So, if you can add the old pagination mode as an alternative reading mode for those who wanted, that would be great. 😊

**Comment by Cambridgeport90** [comment]
This might be a little bit of a tangent, but how does pagination work in ePub formatted files, anyway? I know that Kindle can mimic the page structure of the printed page, and aren't they just encrypted Epub?
