### ISSUE TITLE
Ability to choose the font for the book's content

### ISSUE THREAD

**Issue by k-kolev1985** [blindpandas/bookworm#55]
## Is your feature request related to a problem? Please describe
Yes, my feature request is related to a problem. I rarely come across such e-books, but there are a few of them, in which the text has some characters that standard fonts (e.g. Segoe UI) do not support. In such cases, the e-book requires the usage of other fonts (e.g. Dejavu), that do support such non-standard (Unicode) characters.

## Describe the solution you'd like
I would like for Bookworm to have an option to choose which font is used for displaying the e-book's content (the text area on the right). If possible, that could be extended to the "Table of contents" tree view area on the left as well.

## Describe alternatives you've considered
I don't think there are alternatives, except maybe for using another e-book reading program, which provides the ability to choose which font is used for displaying the e-book's content (e.g. Balabolka). But such a solution in this case is besides the point - isn't it (?). 😀

**Comment by mush42** [comment]
Hi @k-kolev1985 

This feature is on my radar for a while. I'll implement it when I finish the current work on cross-platform support.

Thanks,
