### ISSUE TITLE
Bookworm alpha has problem "escaping" some characters

### ISSUE THREAD

**Issue by k-kolev1985** [blindpandas/bookworm#56]
## Describe the Problem
While reading a book in the alpha version of Bookworm, I've noticed that while displaying the text, it has problems "escaping" some characters. In particular - the backslash (\). When there is a sequence of characters such as for example "YES\NO", Bookworm alpha displays it as "YES\\u041dO". Actually, the text is in bulgarian. It should display as "ДА\НЕ", but it displays as "ДА\\u041dЕ". Apparently Bookworm displays the character "Н" by its hexadecimal unicode representation.

## Steps to reproduce it
1. Launch Bookworm alpha
2. Open a book with text that contains a backslash character and text right before and after it.
3. Find the text and observe how it is displayed.

## Expected behavior
The text string containing the backslash character should be displayed correctly.

## Actual behavior
Bookworm displays part of the string by its hexadecimal unicode representation.

## The File You've Opened
It is an EPUB file. I can attach it here if needs be.

## Desktop (please complete the following information):
 - Operating system: Windows 10 Pro version 20H2 (build 19042.746), 64-bit, in Bulgarian with all locale settings set to "Bulgarian".
 - Bookworm version: 0.2a4.

**Comment by mush42** [comment]
Noted and will be fixed

**Comment by mush42** [comment]
Hi @k-kolev1985 
Based on my own testing this issue has been fixed in Bookworm 0.3 which will be released shortly.
Also we're now using a new technique to fix unicode issues.
