### ISSUE TITLE
The preferences dialog doesn't open

### ISSUE THREAD

**Issue by Futyn-Maker** [blindpandas/bookworm#57]
## Describe the Problem
I can't open the preferences dialog. When I try to do it, never happen.
A clear and concise description of what the problem is.

## To Reproduce
1. Open the portable app;
2. Try to open the preferences dialog by clicking on this in tools menu or pressing CTRL+Shift+P.
3. See error

## Expected behavior
The preferences dialog should open

## The File You've Opened
Any book or without it at all
Tell us what is the format of the file you've opened [e.g. PDF]. If possible, attach the file you have open in Bookworm when the problem happened.

## Desktop (please complete the following information):

 - OS: [e.g. Windows 10 64-bit]
Windows 10 Pro 64 bit
 - Bookworm version [e.g. 0.1.0b1]
Bookworm version 0.2 A4
 - Recent settings you may have changed in Bookworm [e.g. changed the speech settings]

## Additional context
I use the portable app on my Windows 10 with NVDA. Can't to change any preferences...

**Comment by Futyn-Maker** [comment]
I've edited the issue as I've updated the application to 0.2 A4. The problem is still relevant.

**Comment by Cambridgeport90** [comment]
Same thing happens for me.

**Comment by mush42** [comment]
Hi @Futyn-Maker 

Could you provide the application logs. Follow these steps to obtain the logs:

1. Start Bookworm
2. Reproduce the problem by trying to open the preferences dialog
3. Create a zip archive of the folder: user-config\logs and upload it here


Best regards,

**Comment by cary-rowen** [comment]
Hi, When will you release the next stable version?
Thanks.

**Comment by Futyn-Maker** [comment]
@mush42 download them here:
  http://orbraille.uxp.ru/logs.zip
  I've replaced the version with installed copy.
  As I can see, there's a problem with checking for updates because of the URL hasn't existed anymore.

**Comment by mush42** [comment]
@Futyn-Maker 

The logs show nothing out of the ordinary. Please make sure that you've tried to open the preferences dialog, and that the menssioned issue occured.

Also please start Bookworm with debug mode enabled by selecting the 'Restart with debug mode enabled' from the application's help menu.

Regards,

**Comment by Futyn-Maker** [comment]
@mush42 OK, I see! Something goes wrong with TTS. The error:
```
Traceback (most recent call last):
  File "bookworm\gui\book_viewer\menubar.py", line 217, in onPreferences
  File "bookworm\gui\components.py", line 169, in __init__
  File "bookworm\gui\settings.py", line 323, in addControls
  File "bookworm\gui\settings.py", line 317, in addPanels
  File "bookworm\text_to_speech\tts_gui.py", line 141, in __init__
  File "bookworm\gui\settings.py", line 162, in __init__
  File "bookworm\text_to_speech\tts_gui.py", line 209, in addControls
  File "bookworm\text_to_speech\tts_gui.py", line 220, in configure_with_engine
  File "bookworm\speechdriver\engines\sapi\sp_engine.py", line 63, in get_voices
AttributeError: 'NoneType' object has no attribute 'IetfLanguageTag'
```

**Comment by Futyn-Maker** [comment]
@mush42 any news about this problem?

**Comment by Futyn-Maker** [comment]
@mush42 Thanks for fix! Can You , please, release next version with these fixes? I didn't succeed in building the app by myself.
