### ISSUE TITLE
Linux support?

### ISSUE THREAD

**Issue by ethindp** [blindpandas/bookworm#59]
## Is your feature request related to a problem? Please describe.

Bookworm is, from what I can gather, only available on Windows.

## Describe the solution you'd like

Bookworm can reach even more people by becoming cross-platform. So long as it doesn't use any platform-specific code (I haven't verified this) it shouldn't be too difficult to be made cross-platform. In particular, calls to accessibility/screen reader APIs can be replaced with calls to speech-dispatcher for TTS.

## Describe alternatives you've considered

Bookworm could be ran in wine, but Linux accessibility APIs and screen readers cannot function in such an environment.

## Additional context

I'd love to be able to use Bookworm on Linux. I'm using Linux as my main driver now, and have lots of PDFs and EPUBs that I would need to use (alternative) tools to read -- tools like Calibre. I'm not a fan of these tools, however.

**Comment by mush42** [comment]
Hi,
Bookworm builds and runs on linux alright, last tested 3 months ago.
The only problem is that wx widgets is not accessible on linux. At least based on my testing.
Any thoughts?

**Comment by MesterPerfect** [comment]
@mush42
Wx library doesn't work well in linux
The solution is to design a different GUI using QT5 or Tkinter
QT5 includes an application designer.exe which can be used to create a graphical user interface without writing any code

**Comment by ethindp** [comment]
Don't use tkinter if you want an accessible user interface. Instead,
either use QT5 (not recommended) or GTK.

On 5/23/21, MesterPerfect ***@***.***> wrote:
> @mush42
> Wx library doesn't work well in linux
> The solution is to design a different GUI using QT5 or Tkinter
> QT5 includes an application designer.exe which can be used to create a
> graphical user interface without writing any code
>
> --
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/blindpandas/bookworm/issues/59#issuecomment-846515072


-- 
Signed,
Ethin D. Probst

**Comment by mush42** [comment]
Hi all,

I'm aware that GTK is the most accessible GUI toolkit on Linux today. Specially the latest version, GTK4.

Rewriting the GUI layer of Bookworm to use multiple GUI backends is quite an undertaking.

Unless someone volunteer to oversee this work, or someone sponsor it financially, I could not guarantee that Linux support will happen soon.

With our limited resources, it is better to make a great document reader for Windows, rather than making a mediocre cross-platform one.

Regards,

**Comment by ethindp** [comment]
To my knowledge, GTK4 does not yet have any accessibility whatsoever.
I've tried using GTK4 apps in the past and Orca couldn't even work
with them.

On 5/23/21, Musharraf ***@***.***> wrote:
> Hi all,
>
> I'm aware that GTK is the most accessible GUI toolkit on Linux today.
> Specially the latest version, GTK4.
>
> Rewriting the GUI layer of Bookworm to use multiple GUI backends is quite an
> undertaking.
>
> Unless someone volunteer to oversee this work, or someone sponsor it
> financially, I could not guarantee that Linux support will happen soon.
>
> With our limited resources, it is better to make a great document reader for
> Windows, rather than making a mediocre cross-platform one.
>
> Regards,
>
> --
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/blindpandas/bookworm/issues/59#issuecomment-846613353


-- 
Signed,
Ethin D. Probst

**Comment by mush42** [comment]
Hello all,

The main issue here is that WxPython is not very accessible on Linux, tested on Ubuntu 20.04.

The core of Bookworm, e.g. document parsing, document structure, searching..etc is fairly platform agnostic, and Windows  specific features are enabled conditionally using a boolean flag.

I'm eager to see a Linux port of Bookworm, and I can even help with that. But currently, I'm focusing on improving the experience on Windows and making it the best it could be.

Best
Musharraf
