### ISSUE TITLE
Bookworm fails to open a PDF file, if its path contains cyrillic characters

### ISSUE THREAD

**Issue by k-kolev1985** [blindpandas/bookworm#63]
## Describe the Problem

If a PDF file contains cyrillic characters in its file name or path, Bookworm will fail to open it.

## To Reproduce

1. Rename a PDF file or the path to it, so it contains cyrillic characters.
2. Open Bookworm.
3. Try to open in Bookworm the file from step 1. The opening will fail with the error message about the file being corrupted. But if the file name or the path to it do not contain cyrillic characters, the error will not be displayed and the file will be opened successfully.

## Expected behavior

Bookworm should be able to open the file, no matter what type of characters do its file name or path contain.

## The File You've Opened

It is a PDF file. Not a specific one. It has to have cyrillic characters either in its file name or its path. I can provide such a file, if needs be. Also, I can provide the logs from Bookworm, if needs be.

## Desktop (please complete the following information):

 - OS: Windows 10 Pro version 20H2 (build 19042.985), 64-bit, in Bulgarian with all locale settings set to "Bulgarian".
 - Bookworm version 0.4b1, in english.

## Additional context

The problem does not occur with the last stable release of Bookworm - only with the test/beta builds.

**Comment by fawazar94** [comment]
Hello, 
This issue is still there in the last released version on the website, 0.4B1, with Arabic name / name in the path. 
and still happens only with PDF, once you rename the file, it works perfectly. 
thanks.

**Comment by mush42** [comment]
Hi @k-kolev1985  and @fawazar94

I tried to reproduce this with Arabic names in directory and filename and no problems occurred.

Please help me with this by describing how you're trying to open the document: from Explorer or from within Bookworm?

Please also restart the application with debug mode enabled and upload the logs.

Regards,

**Comment by fawazar94** [comment]
Hello, 
I just renamed a book I was reading to "تجربة" and it failed to open, neither from the explorer nor from within the app. 
from the folder I tried open with then bookworm, from the app I tried control+O. same error. 
thanks.

**Comment by fawazar94** [comment]
sorry, here is the log: 
https://www.dropbox.com/s/nyh4s3lbym7o8j6/logs.zip?dl=0

**Comment by k-kolev1985** [comment]
I'm opening the PDF file via Control+O from within Bookworm itself. I haven't associated PDF files with Bookworm, so I can't open them with it via a file manager like Windows Explorer. I'm attaching the logs created 
[Bookworm_Logs_2021-05-29.zip](https://github.com/blindpandas/bookworm/files/6564349/Bookworm_Logs_2021-05-29.zip)
with debug mode enabled.

**Comment by mush42** [comment]
Hi all,

That was very helpful. Thanks.
