### ISSUE TITLE
duplicate entries for Arabic in preferences

### ISSUE THREAD

**Issue by mohdshara** [blindpandas/bookworm#70]
## Describe the Problem

There are 2 duplicate entries for Arabic in the preferences dialogue box: Arabic and Arabic (Sudan). Arabic (Sudan) is more update in terms of translation.

## To Reproduce

1. go to the preferences dialogue box.
2. in the general sheet, and under interface language, there are 2 entries for Arabic.
3. Arabic (Sudan) is more updated.

## Expected behavior

1 entry should exist for Arabic, preferably named just (Arabic) without specifying the locale, and it should be up to date.

## The File You've Opened

irrelevant

## Desktop (please complete the following information):

 - OS: Windows 10 64-bit
 - Bookworm version 0.4.0b1
 - Recent settings you may have changed in Bookworm change interface language

## Additional context

none

**Comment by pauliyobo** [comment]
Hello.
@mohdshara Do you still encounter this problem in the most recent build?

**Comment by mohdshara** [comment]
hi.

No. There are no longer multiple entries for Arabic. However, I propose
that the language name is changed into "Arabic" and not "arabic Sudan".

Thanks.
Mohammed.
