### ISSUE TITLE
can I translate into italian?

### ISSUE THREAD

**Issue by dreinn** [blindpandas/bookworm#71]
Hello,
I'd like to know if I can translate this excellent software  into italian.
I have a good experience since I'm translating the NVDA screen reader from 2009.
Let me know what I can do, thank you!

**Comment by mush42** [comment]
Hi @dreinn 

Thanks for taking the initiative. Please provide me with your email address by sending a message to info@blindpandas.com

**Comment by dreinn** [comment]
hello, I wrote you in the past at that email but no answer...
I rewrote yesterday sending you the .po file, can you check the email please?
Thank you!

**Comment by mush42** [comment]
Hello @dreinn 

Sorry for the inconvenience, the email above has been taken over by some entity due to our failure to renew the domain.

Please resend to the following email address:
musharraf.omer@gmail.com

Best
Musharraf
