### ISSUE TITLE
Simplified Chinese language is not loaded in Bookworm-0.4b1

### ISSUE THREAD

**Issue by cary-rowen** [blindpandas/bookworm#72]
## Describe the Problem

Simplified Chinese language is not loaded in Bookworm-0.4b1

## To Reproduce

1. Go to 'Bookworm Preferences';
2. Click on 'Display Language';
3. Select 'Chinese (Simplified, China)';
4. Click'OK' and then click 'Yes' to restart bookworm;
5. After restarting, it will be displayed in English. Go to the settings again to see that the current language is still'English'

## Expected behavior
After performing step (4), the interface changes to simplified Chinese.

## The File You've Opened
None

## Desktop (please complete the following information):

 - OS: [Windows 10 64-bit]
 - Bookworm version [0.4b1]
 - Recent settings you may have changed in Bookworm [Display Language]

## Additional context
None

**Comment by cary-rowen** [comment]
Is there any update to this project?

**Comment by cary-rowen** [comment]
This issue has been resolved in the latest alpha version, So, I want to close it. Also, I want the latest version to include full simplified Chinese translation, how can I do that?

**Comment by mush42** [comment]
Hi @cary-rowen 

You can download the translation template of the latest version from the [releases page.](https://github.com/blindpandas/bookworm/releases/). In the assets section there is a file named bookworm.pot that contains all of the messages.

But holdout for now. Messages in the above mentioned file do not contain proper translators comments, and they're subject to change. before we release the first beta of v2022.1 we'll send you an email.

Regards,

**Comment by cary-rowen** [comment]
@mush42 
Thanks again, I see, I was also wondering which way would you prefer to receive translations, open a PR or Crowdin?

**Comment by mush42** [comment]
Hi @cary-rowen 

You've three alternatives:

* Open a PR
* * Open an issue and upload the *.po file
* * Send it via email to (info(at)blindpandas.org)

Regards,
