### ISSUE TITLE
.doc support

### ISSUE THREAD

**Issue by vortex1024** [blindpandas/bookworm#77]
all books made available by a specialized library in my country are supplied in .doc format.
## Describe the solution you'd like
implementation of the .doc format in bookworm. It seems there are several pyton libraries providing it.

**Comment by cary-rowen** [comment]
Now bookworm supports opening word documents in .docx format. Is this what you want? If so, you may be able to close this issue.

**Comment by vortex1024** [comment]
only docx, or doc, also? Doc is what I was asking for...

**Comment by mush42** [comment]
I've no time to dig into this further. It seams that .doc is a niche format, and I'd rather invest my effort elsewhere.
Unless, of course, a library or a program is available, then I can revisit this again.

Best

**Comment by vortex1024** [comment]
I tested this, it works, even though it is quite old
https://github.com/rembish/Miette
alternatively, a windows only solution is using ifilter through pywin32. this will give you way more formats.

**Comment by mush42** [comment]
Hi @vortex1024  @cary-rowen 

It seams that we can support .doc documents after all. Track progress in the **word_doc** branch.

As a bonus, we'll add support for docbook: a format for writing technical documentation.

Best

**Comment by cary-rowen** [comment]
Thanks @mush42 I'm glad to see the bookworm grow.

**Comment by cary-rowen** [comment]
Hi @mush42 

Does 2022.1B1 confirm that .doc documents are already supported?

I get an error when I try to open a .doc document:

Could not open Document.
The document does not exist.

Support for word 97 2003 documents is indeed listed in the open file filter.

Thanks

**Comment by mush42** [comment]
@cary-rowen 
Support for .doc format has not been finalized yet.
Please provide the full log.

**Comment by cary-rowen** [comment]
Hi @mush42 ,

Bookworm reports the following error:
Could not open Document.
The document does not exist.

[test_OpenDoc.zip](https://github.com/blindpandas/bookworm/files/8153178/test_OpenDoc.zip)
