### ISSUE TITLE
tasks.py code update

### ISSUE THREAD

**Issue by mystragical** [blindpandas/bookworm#81]
## Describe the Problem
While issuing the command "Invoke dev" in the development environment, an error saying "cp is not recognized as an internal command" comes up.

## To Reproduce
Go through the steps mentioned in the development guide in the read me section, and observe once the "invoke dev" command is entered.

## Expected behavior
It should build the bookworm software, without giving that error.

## The File You've Opened
I've narrowed down the issue to tasks.py in the build environment folder.

## Desktop (please complete the following information):

 - OS: [Windows 11 21H2 (x64) build 22000.318]
 - Bookworm version [e.g. 0.1.0b1]
 - Recent settings you may have changed in Bookworm [n/a]

## Additional context
Changing the cp commands in the tasks.py file solves the problem. I changed it to copy.
I am learning how to make pull requests yet, so filing it here, before attempting to make the pull request.

**Comment by mystragical** [comment]
[tasks.txt](https://github.com/blindpandas/bookworm/files/7613816/tasks.txt)

**Comment by mystragical** [comment]
Added the updated tasks.txt file, since .py wasn't getting uploaded.
[tasks.txt](https://github.com/blindpandas/bookworm/files/7613818/tasks.txt)

**Comment by mush42** [comment]
Hi @mystragical 

To allow for cross platform builds, we rely on the standard POSIX shell utilities. Unfortunately, those tools aren't available on Windows by default, you need to add them manually.

The easiest way of adding POSIX tools to Windows is to use the ones that come with every standard Git installation. For instance, in my computer I added the following directory to my PATH environment variable:
"C:\Program Files\Git\mingw64\bin"

After this the 'cp' command will be available to Bookworm's build system.

Regards,
