### ISSUE TITLE
Screen curtain and Bookworm problem

### ISSUE THREAD

**Issue by mystragical** [blindpandas/bookworm#86]
## Description of the problem:
Whenever bookworm is running and screen curtain of NVDA is enabled, switching to other app with Alt-tab or switching to bookworm from other app causes screen curtain of NVDA to get automatically disabled.

## To Reproduce
1. Open Bookworm. It could be just bookworm, or any book opened in bookworm.
2. Enable screen curtain of NVDA.
3. Switch to other apps with Alt+tab.
4. Check if NVDA's screen curtain state changes.
## Expected behavior
Screen curtain state is supposed to remain unchanged.

## The File You've Opened
It can happen without opening any book file. Just open the bookworm from desktop or the bookworm.exe
Tell us what is the format of the file you've opened [e.g. PDF]. If possible, attach the file you have open in Bookworm when the problem happened.
Not applicable
## Desktop 
OS: Windows 11 21H2 (x64) build 22000.376
Bookworm version [0.4b1]
 - Recent settings you may have changed in Bookworm [e.g. changed the speech settings]
I don't recall if I changed any settings in bookworm.
## Additional context
At this point, I am not sure if this is Bookworm issue or NVDA issue, but since it's only happening with Bookworm, I am filing the issue here. The issue persists in debug mode as well, I don't know where the logs are located.

**Comment by mush42** [comment]
Hi @mystragical 

I think this has nothing to do with Bookworm.

Would you mind checking your NVDA's config profiles. Maybe you have enabled a custom profile for Bookworm and forgot about it. If so, remove the custom profile and try again.

Please don't hesitate to re open if you think this is really about Bookworm.

Regards,
