### ISSUE TITLE
Allow invalid items to be removed from the recently opened list

### ISSUE THREAD

**Issue by cary-rowen** [blindpandas/bookworm#90]
## Is your feature request related to a problem? Please describe.
If I change a book's location or delete a book, I can't open it again in "Recently Opened" and certainly can't remove it from the list

## Describe the solution you'd like
In addition to the existing "Clear list" option, add a "Clear Invalid Items" option
## Describe alternatives you've considered
Or consider adding "Yes" and "No" buttons to the "Document not found" dialog to remove invalid items
## Additional context
None

**Comment by mush42** [comment]
Hi @cary-rowen 

This is a provider wide action. I've added it to the File menu in the application menu bar.

Regards,

**Comment by cary-rowen** [comment]
Wow, thanks again for your efforts.

**Comment by cary-rowen** [comment]
Hi @mush42 

The issue doesn't seem to be fully resolved, currently there is an item "Clear invalid documents..." in Bookshelf's file menu, however, there is no such function in Bookworm's file menu.
We still have no way to clear the invalid items in "Recently Opened" and "Pinned Documents" in Bookworm's File menu.

So, allow me to reopen it.

Thanks
