### ISSUE TITLE
Bookworm doesn't download tesseract ocr.

### ISSUE THREAD

**Issue by shaxzodxasanov** [blindpandas/bookworm#94]
Failed to parse Tesseract download information. Please try again.

**Comment by Sumanadhikari72** [comment]
Ok than how can I use it. I have find teseract OCR in preferences.

**Comment by shaxzodxasanov** [comment]
you can on f4 key extract text from images or pdf files. Tesseract is ocr program. at first you need to install tesseract.

**Comment by Sumanadhikari72** [comment]
Ok thanks. From where I can get it?

**Comment by mush42** [comment]
Hi @shaxzodxasanov 

It seams that our servers are down. I'll re upload and update the links in the next release.

Thanks for reporting

**Comment by Sumanadhikari72** [comment]
Ok, I am waiting for it. My another request, Please create telegram channel or group for bookworm where we can get information about it. For example, when a new update comes, we can know about it from telegram. This is just my request.
