### ISSUE TITLE
Page down key doesn't work properly

### ISSUE THREAD

**Issue by adkurz** [blindpandas/bookworm#97]
## Describe the Problem

In a Epub file, if I press the page down key, Book worm jumps to the end of the complete book, not only a few lines downward. The page up key works perfectly.

## To Reproduce

1. Open a epub file in bookworm.
2. Go to the document content edit field.
3. Press the page down key

## Expected behavior

Bookworm should jump only a few lines downward.

## The File You've Opened

Tested with different epub files.

## Desktop (please complete the following information):

 - OS: Windows 10 and 11 64-bit
 - Bookworm version 2022.1a5
 - Recent settings Default settings

**Comment by DraganRatkovich** [comment]
@adkurz Faced the same problem in .doc, .pdf files. @mush42

**Comment by mush42** [comment]
Hello all,

Still investigating the issue. No clues yet!

Best
Musharraf
